export const periodicTableTextPt = {
  common: {
    close: 'Fechar',
    loading: 'Carregando...',
    yes: 'Sim',
    no: 'Não',
    showingCountPrefix: 'Mostrando',
    showingCountMiddle: 'de',
    showingCountSuffix: 'elementos',
  },
  explore: {
    searchLabel: 'Pesquisar',
    searchPlaceholder: 'Nome, símbolo, número, fase, categoria...',
    sortLabel: 'Ordenar',
    luckySearch: 'Busca aleatória',
    clear: 'Limpar',
    viewLabel: 'Visualização',
    updatingView: 'Atualizando resultados...',
    dedicatedModeMessage: 'Clique em qualquer elemento para abrir os detalhes.',
  },
  menus: {
    sortOptions: 'Opções de ordenação',
    viewOptions: 'Opções de visualização',
    toggleSort: 'Alternar opções de ordenação',
    toggleView: 'Alternar opções de visualização',
  },
  viewOptions: {
    classic: 'Clássica',
    category: 'Categoria',
    compact: 'Compacta',
  },
  sortOptions: {
    number: 'Número atômico',
    name: 'Nome',
    symbol: 'Símbolo',
    mass: 'Massa atômica',
  },
  fullscreen: {
    zoomOut: 'Reduzir zoom da tabela',
    zoomIn: 'Aumentar zoom da tabela',
    enterTable: 'Abrir tabela em tela cheia',
    exitTable: 'Sair da tabela em tela cheia',
    enter: 'Tela cheia',
    exit: 'Sair da tela cheia',
  },
  details: {
    emptyTitle: 'Detalhes do Elemento',
    sectionTitle: 'Detalhes do Elemento',
    dataTitle: 'Dados do Elemento',
    tableView: 'Ver tabela',
    cardView: 'Ver cartões',
    field: 'Campo',
    value: 'Valor',
    previousElement: 'Elemento anterior',
    nextElement: 'Próximo elemento',
    closeExpandedImage: 'Fechar imagem ampliada',
    externalLinksTitle: 'Links Externos',
    links: {
      officialSource: 'Fonte oficial',
      elementImage: 'Imagem do elemento',
      bohr2d: 'Bohr 2D',
      bohr3d: 'Bohr 3D',
      spectralImage: 'Imagem espectral',
      open3dFile: 'Abrir arquivo 3D',
    },
    badges: {
      radioactive: 'Radioativo',
    },
    viewer: {
      elementImage: 'Imagem do elemento',
      bohr: 'Bohr',
      modelUnavailable: 'Modelo 3D indisponível para este elemento.',
      loading3d: 'Carregando visualização 3D...',
    },
    fields: {
      name: 'Nome',
      symbol: 'Símbolo',
      atomicNumber: 'Número atômico',
      atomicMass: 'Massa atômica',
      category: 'Categoria',
      phase: 'Fase',
      group: 'Grupo',
      period: 'Período',
      block: 'Bloco',
      appearance: 'Aparência',
      density: 'Densidade',
      boilingPoint: 'Ponto de ebulição',
      meltingPoint: 'Ponto de fusão',
      molarHeat: 'Calor molar',
      electronAffinity: 'Afinidade eletrônica',
      electronegativityPauling: 'Eletronegatividade (Pauling)',
      electronConfiguration: 'Configuração eletrônica',
      electronConfigSemantic: 'Configuração eletrônica (semântica)',
      ionizationEnergies: 'Energias de ionização',
      shells: 'Camadas',
      discoveredBy: 'Descoberto por',
      namedBy: 'Nomeado por',
      cpkHex: 'CPK Hex',
      tablePositionX: 'Posição X na tabela',
      tablePositionY: 'Posição Y na tabela',
      widePositionX: 'Posição X ampla',
      widePositionY: 'Posição Y ampla',
      imageTitle: 'Título da imagem',
      imageAttribution: 'Crédito da imagem',
      summary: 'Resumo',
      notInformed: 'Não informado',
    },
  },
} as const;
