export const periodicTableTextEn = {
  common: {
    close: 'Close',
    loading: 'Loading...',
    yes: 'Yes',
    no: 'No',
    notAvailableShort: 'n/a',
    showingCountPrefix: 'Showing',
    showingCountMiddle: 'of',
    showingCountSuffix: 'elements',
  },
  tile: {
    openDetailsPrefix: 'Open details of',
    radioactiveElement: 'Radioactive element',
    phase: {
      solid: 'Solid',
      liquid: 'Liquid',
      gas: 'Gas',
      unknown: 'Unknown',
    },
  },
  taxonomy: {
    categories: {
      alkaliMetal: 'Alkali metal',
      alkalineEarthMetal: 'Alkaline earth metal',
      transitionMetal: 'Transition metal',
      postTransitionMetal: 'Post-transition metal',
      metalloid: 'Metalloid',
      nonmetal: 'Nonmetal',
      halogen: 'Halogen',
      nobleGas: 'Noble gas',
      lanthanide: 'Lanthanide',
      actinide: 'Actinide',
      unknown: 'Unknown',
      other: 'Other',
    },
  },
  explore: {
    searchLabel: 'Search',
    searchPlaceholder: 'Name, symbol, number, phase, category...',
    sortLabel: 'Sort',
    luckySearch: 'Lucky Search',
    clear: 'Clear',
    viewLabel: 'View',
    updatingView: 'Updating results...',
    dedicatedModeMessage: 'Click any element to open its details.',
  },
  menus: {
    sortOptions: 'Sort options',
    viewOptions: 'View options',
    toggleSort: 'Toggle sort options',
    toggleView: 'Toggle view options',
  },
  viewOptions: {
    classic: 'Classic',
    category: 'Category',
    compact: 'Compact',
  },
  sortOptions: {
    number: 'Atomic Number',
    name: 'Name',
    symbol: 'Symbol',
    mass: 'Atomic Mass',
  },
  fullscreen: {
    zoomOut: 'Reduce table zoom',
    zoomIn: 'Increase table zoom',
    enterTable: 'Enter fullscreen table',
    exitTable: 'Exit fullscreen table',
    enter: 'Fullscreen',
    exit: 'Exit fullscreen',
  },
  details: {
    emptyTitle: 'Element Details',
    sectionTitle: 'Element Details',
    dataTitle: 'Element Data',
    tableView: 'Table View',
    cardView: 'Card View',
    field: 'Field',
    value: 'Value',
    previousElement: 'Previous element',
    nextElement: 'Next element',
    closeExpandedImage: 'Close expanded image',
    externalLinksTitle: 'External Links',
    links: {
      officialSource: 'Official Source',
      elementImage: 'Element Image',
      bohr2d: 'Bohr 2D',
      bohr3d: 'Bohr 3D',
      spectralImage: 'Spectral Image',
      open3dFile: 'Open 3D file',
    },
    badges: {
      radioactive: 'Radioactive',
    },
    viewer: {
      elementImage: 'Element Image',
      bohr: 'Bohr',
      modelUnavailable: '3D model unavailable for this element.',
      loading3d: 'Loading 3D view...',
    },
    fields: {
      name: 'Name',
      symbol: 'Symbol',
      atomicNumber: 'Atomic Number',
      atomicMass: 'Atomic Mass',
      category: 'Category',
      phase: 'Phase',
      group: 'Group',
      period: 'Period',
      block: 'Block',
      appearance: 'Appearance',
      density: 'Density',
      boilingPoint: 'Boiling Point',
      meltingPoint: 'Melting Point',
      molarHeat: 'Molar Heat',
      electronAffinity: 'Electron Affinity',
      electronegativityPauling: 'Electronegativity (Pauling)',
      electronConfiguration: 'Electron Configuration',
      electronConfigSemantic: 'Electron Config (Semantic)',
      ionizationEnergies: 'Ionization Energies',
      shells: 'Shells',
      discoveredBy: 'Discovered By',
      namedBy: 'Named By',
      cpkHex: 'CPK Hex',
      tablePositionX: 'Table Position X',
      tablePositionY: 'Table Position Y',
      widePositionX: 'Wide Position X',
      widePositionY: 'Wide Position Y',
      imageTitle: 'Image Title',
      imageAttribution: 'Image Attribution',
      summary: 'Summary',
      notInformed: 'Not informed',
    },
  },
} as const;
