export const adminWorkspaceTextPt = {
  shell: {
    badge: 'Controle ADMIN',
    title: 'Painel de operações para trabalho protegido.',
    description:
      'Revise áreas protegidas, inspecione fluxos de conteúdo e prepare o gerenciamento de usuários sem expor ferramentas inacabadas para visitantes comuns.',
    navigationLabel: 'Áreas admin',
    currentAdminLabel: 'Admin atual',
    featureStageLabel: 'Estágio do Article',
    featureStageStates: {
      off: 'Desligado',
      internal: 'Interno',
      public: 'Público',
    },
    serverGuardLabel: 'Modo de guarda',
    serverGuardValue: 'Negação padrão no servidor',
  },
  sections: {
    overview: {
      navLabel: 'Visão geral',
      title: 'Visão geral admin',
      description: 'Sala de controle para rotas protegidas, visibilidade de features e próximas ações operacionais.',
    },
    users: {
      navLabel: 'Usuários',
      title: 'Gerenciamento de usuários',
      description: 'Estruture os fluxos mais comuns de administração de contas com reporte seguro de status.',
    },
    access: {
      navLabel: 'Acesso',
      title: 'Acesso e guardrails',
      description: 'Acompanhe quais rotas estão protegidas, como isso é imposto e o que está visível neste momento.',
    },
    content: {
      navLabel: 'Conteúdo',
      title: 'Operações de conteúdo',
      description: 'Opere previews de artigos, checagens de moderação e políticas de segurança de conteúdo em um só lugar.',
    },
  },
  common: {
    name: 'Nome',
    email: 'E-mail',
    role: 'Função',
    contract: 'Contrato',
    status: 'Status',
    access: 'Acesso',
    guard: 'Proteção',
    visibility: 'Visibilidade',
    surface: 'Superfície',
    dependency: 'Dependência',
    securityNote: 'Nota de segurança',
  },
  overview: {
    cards: {
      adminAreas: 'Áreas admin',
      protectedRoutes: 'Rotas protegidas',
      articleMode: 'Modo do Article',
      authSource: 'Fonte de auth',
    },
    authSourceValue: 'Upstream de auth direto + fallback por token espelhado',
    quickActionsTitle: 'Ações rápidas',
    quickActionsDescription: 'Salte direto para as áreas protegidas mais úteis durante desenvolvimento e moderação.',
    openUsers: 'Abrir área de usuários',
    openAccess: 'Revisar guardrails',
    openContent: 'Abrir operações de conteúdo',
    openArticleFeed: 'Abrir feed de artigos',
    openArticleWorkspace: 'Abrir workspace de artigos',
    openArticleEditor: 'Abrir editor de artigos',
    articleUnavailable: 'O Article System está desligado neste ambiente, então as ações de preview de conteúdo ficam desabilitadas aqui.',
    readinessTitle: 'Prontidão operacional',
    readinessDescription: 'Este painel já está pronto para uso interno seguro. As mutações de usuários ainda aguardam endpoints administrativos dedicados no backend.',
  },
  users: {
    searchLabel: 'Buscar capacidades',
    searchPlaceholder: 'Busque por capacidade, ação ou dependência',
    applyFilters: 'Aplicar filtros',
    clearFilters: 'Limpar filtros',
    filterStatusLabel: 'Filtro de status',
    filterTrackLabel: 'Trilha operacional',
    summaryCards: {
      visible: 'Operações visíveis',
      available: 'Pronto agora',
      guarded: 'Protegido agora',
      planned: 'Aguardando backend',
    },
    currentAdminTitle: 'Registro do admin atual',
    currentAdminDescription: 'Este workspace usa o perfil ADMIN atuante como âncora de autoridade viva para cada rota protegida.',
    liveGuardrailsTitle: 'Guardrails de usuários já ativos',
    liveGuardrails: [
      'Rotas admin continuam protegidas no servidor e negam por padrão quando a resolução da sessão fica incerta.',
      'Previews internos de Article seguem invisíveis para não-admins e renderizam pela 404 compartilhada.',
      'Mudanças de papel e ações de moderação continuam bloqueadas até existirem contratos auditáveis no backend.',
    ],
    capabilitiesTitle: 'Operações comuns de administração de usuários',
    capabilitiesDescription: 'Use esta visão para separar o que já está vivo, o que já está protegido e o que ainda precisa de autoridade real do backend antes de liberar.',
    empty: 'Nenhuma capacidade admin combinou com esta busca.',
    emptyFiltered: 'Nenhuma operação admin combina com os filtros atuais.',
    statuses: {
      available: 'Pronto agora',
      planned: 'Depende do backend',
      guarded: 'Fundação protegida',
    },
    statusFilters: {
      all: 'Todos os status',
      available: 'Pronto agora',
      guarded: 'Protegido',
      planned: 'Depende do backend',
    },
    trackFilters: {
      all: 'Todas as trilhas',
      session: 'Sessão',
      access: 'Acesso',
      directory: 'Diretório',
      roles: 'Papéis',
      moderation: 'Moderação',
      audit: 'Auditoria',
    },
    capabilityItems: {
      resolveSession: {
        title: 'Resolver a sessão admin atual',
        description: 'O acesso server-side já confirma que o usuário atuante é ADMIN antes de renderizar o painel.',
        dependency: 'Validação direta no upstream de auth',
        securityNote: 'Isto já está ativo e nega por padrão quando a auth é incerta.',
        contract: 'GET /auth/profile',
      },
      openProtectedAreas: {
        title: 'Abrir áreas exclusivas de admin com segurança',
        description: 'Painéis profissionais de admin precisam separar com clareza rotas públicas e internas.',
        dependency: 'Guards atuais das rotas admin',
        securityNote: 'Superfícies protegidas entregam 404 para não-admins.',
        contract: 'GET /[locale]/admin/*',
      },
      listUsers: {
        title: 'Listar usuários da plataforma',
        description: 'Um diretório dedicado de usuários deve expor paginação, filtros e apenas campos mínimos de identidade.',
        dependency: 'Endpoint administrativo de usuários no backend',
        securityNote: 'Nunca pode confiar em mudanças de papel no client nem em queries sem limite.',
        contract: 'GET /api/v1/admin/users?cursor=...',
      },
      changeRole: {
        title: 'Alterar função do usuário',
        description: 'Promover ou rebaixar usuários por ações administrativas auditadas e com confirmação explícita.',
        dependency: 'Endpoint de mutação de papel no backend',
        securityNote: 'Precisa de autorização server-side, trilha de auditoria e regras para autoproteção.',
        contract: 'POST /api/v1/admin/users/{user_id}/role',
      },
      suspendAccount: {
        title: 'Suspender ou restringir contas',
        description: 'Fluxos comuns de admin normalmente incluem restrições temporárias de conta e passos de recuperação.',
        dependency: 'Endpoints de moderação no backend',
        securityNote: 'Precisa de lógica clara de recurso e recuperação antes de liberar.',
        contract: 'POST /api/v1/admin/users/{user_id}/moderation',
      },
      auditTrail: {
        title: 'Revisar trilha de auditoria admin',
        description: 'Painéis profissionais de admin precisam de histórico limitado para mudança de papéis, moderação e decisões de acesso protegido.',
        dependency: 'Endpoint backend de trilha de auditoria',
        securityNote: 'Os logs devem ser append-only, filtráveis e isolados do tráfego público.',
        contract: 'GET /api/v1/admin/audit?cursor=...',
      },
    },
    contractsTitle: 'Contratos de backend para destravar',
    contractsDescription: 'Estes são os endpoints admin limitados que valem ser construídos agora se você quiser mover este painel de planejamento protegido para operação real de contas.',
    contractItems: {
      directory: {
        title: 'Diretório de usuários',
        endpoint: 'GET /api/v1/admin/users?cursor=...',
        note: 'Retorne apenas campos mínimos de identidade, papel, status e filtros limitados. Nada de varredura sem limite.',
      },
      roleChange: {
        title: 'Mudança de papel',
        endpoint: 'POST /api/v1/admin/users/{user_id}/role',
        note: 'Exige confirmação explícita, regras de autoproteção e um registro de auditoria para cada mutação.',
      },
      moderation: {
        title: 'Restrição de conta',
        endpoint: 'POST /api/v1/admin/users/{user_id}/moderation',
        note: 'Precisa suportar restrições temporárias, reversão, atribuição do ator e captura de motivo.',
      },
      audit: {
        title: 'Trilha de auditoria',
        endpoint: 'GET /api/v1/admin/audit?cursor=...',
        note: 'Exponha histórico operacional append-only com paginação por cursor e acesso limitado por papel.',
      },
    },
  },
  access: {
    summaryTitle: 'Resumo dos guardrails',
    summaryDescription: 'Superfícies internas são protegidas no servidor, ficam fora de indexação e são negadas por padrão sempre que a auth estiver incerta.',
    matrixTitle: 'Matriz de proteção de rotas',
    matrixDescription: 'Esta matriz reflete a política de acesso atualmente imposta pelo frontend.',
    states: {
      serverAdmin: 'Checagem admin no servidor',
      featureStage: 'Gate por estágio da feature',
      noindex: 'Noindex',
      publicWhenReleased: 'Público quando liberado',
      disabled: 'Desligado / 404',
    },
    accessRules: {
      adminOnly: 'Somente ADMIN',
      articleInternal: 'Somente ADMIN enquanto estiver interno',
      articlePublic: 'Feed e detalhe públicos, workspace do dono autenticado',
      unavailable: 'Indisponível',
    },
  },
  content: {
    operationsTitle: 'Operações de conteúdo',
    operationsDescription: 'Use estes atalhos e políticas para inspecionar o Article System sem expor conteúdo inacabado publicamente.',
    openFeed: 'Abrir preview do feed',
    openWorkspace: 'Abrir workspace',
    openEditor: 'Abrir editor',
    disabled: 'O Article System está desligado aqui, então os atalhos de operação de conteúdo ficam indisponíveis.',
    policyTitle: 'Checklist de segurança de conteúdo',
    policyDescription: 'Estes são os guardrails ativos que mais importam para a administração de conteúdo hoje.',
    policies: {
      markdown: 'HTML bruto continua bloqueado na renderização de Markdown.',
      uploads: 'Uploads seguem restritos a fluxos assinados de PNG, JPEG e WebP.',
      visibility: 'Conteúdo privado não pode vazar para rotas públicas nem metadata.',
      pagination: 'A navegação do feed mantém paginação por cursor em vez de OFFSET.',
    },
  },
} as const;
