export const adminWorkspaceTextEn = {
  shell: {
    badge: 'ADMIN control',
    title: 'Secure operations panel for guarded work.',
    description:
      'Operate protected routes, review account activity, and prepare privileged actions without exposing unfinished tooling to regular visitors.',
    navigationLabel: 'Admin areas',
    currentAdminLabel: 'Current admin',
    featureStageLabel: 'Article stage',
    featureStageStates: {
      off: 'Off',
      internal: 'Internal',
      public: 'Public',
    },
    serverGuardLabel: 'Guard mode',
    serverGuardValue: 'Server-side deny by default',
  },
  sections: {
    overview: {
      navLabel: 'Overview',
      title: 'Admin overview',
      description: 'High-level control room for guarded routes, privileged work, and next security-focused actions.',
    },
    users: {
      navLabel: 'Users',
      title: 'User directory',
      description: 'Review platform accounts through bounded filters, protected access, and audited follow-up actions.',
    },
    audit: {
      navLabel: 'Audit',
      title: 'Audit trail',
      description: 'Inspect privileged activity through bounded search, cursor pagination, and deny-by-default access.',
    },
    access: {
      navLabel: 'Access',
      title: 'Access and guardrails',
      description: 'Track which routes are protected, how they are enforced, and what is currently visible.',
    },
    content: {
      navLabel: 'Content',
      title: 'Content operations',
      description: 'Operate article previews, moderation-oriented checks, and content safety policies from one place.',
    },
  },
  common: {
    name: 'Name',
    email: 'Email',
    role: 'Role',
    status: 'Status',
    createdAt: 'Created',
    updatedAt: 'Updated',
    lastSeenAt: 'Last seen',
    actions: 'Actions',
    query: 'Search',
    sort: 'Sort',
    contract: 'Contract',
    access: 'Access',
    guard: 'Guard',
    visibility: 'Visibility',
    surface: 'Surface',
    dependency: 'Dependency',
    securityNote: 'Security note',
    loading: 'Loading…',
    unavailable: 'Unavailable in this environment.',
    retry: 'Retry',
  },
  overview: {
    cards: {
      adminAreas: 'Admin areas',
      protectedRoutes: 'Protected routes',
      articleMode: 'Article mode',
      authSource: 'Auth source',
    },
    authSourceValue: 'Direct auth upstream + mirrored token fallback',
    quickActionsTitle: 'Quick actions',
    quickActionsDescription: 'Jump directly to the protected areas you are most likely to inspect during development, review, and account operations.',
    openUsers: 'Open users area',
    openAudit: 'Open audit trail',
    openAccess: 'Review guardrails',
    openContent: 'Open content ops',
    openArticleFeed: 'Open article feed',
    openArticleWorkspace: 'Open article workspace',
    openArticleEditor: 'Open article editor',
    articleUnavailable: 'The Article System is off in this environment, so content preview actions stay disabled here.',
    readinessTitle: 'Operational readiness',
    readinessDescription: 'This panel now includes secure admin API wiring, real directory surfaces, and audit groundwork. High-risk mutations still depend on backend enforcement and audit contracts.',
  },
  users: {
    searchLabel: 'Search users',
    searchPlaceholder: 'Search by name, email, or user id',
    roleFilterLabel: 'Role filter',
    statusFilterLabel: 'Status filter',
    sortLabel: 'Sort order',
    applyFilters: 'Apply filters',
    clearFilters: 'Clear filters',
    roleFilters: {
      all: 'All roles',
      USER: 'Users',
      ADMIN: 'Admins',
    },
    statusFilters: {
      all: 'All statuses',
      active: 'Active',
      restricted: 'Restricted',
      suspended: 'Suspended',
    },
    sortOptions: {
      'created-desc': 'Newest first',
      'created-asc': 'Oldest first',
      'last-seen-desc': 'Recently seen',
      'last-seen-asc': 'Least recent',
    },
    summaryCards: {
      visible: 'Visible users',
      admins: 'Admins in page',
      active: 'Active in page',
      restricted: 'Restricted in page',
    },
    tableTitle: 'Protected user directory',
    tableDescription: 'This directory is loaded through the guarded admin API proxy. Missing backend contracts surface as unavailable states instead of fake controls.',
    tableColumns: {
      user: 'User',
      status: 'Status',
      role: 'Role',
      lastSeen: 'Last seen',
      createdAt: 'Created',
    },
    openUser: 'Open record',
    empty: 'No users were returned for this environment yet.',
    emptyFiltered: 'No users match the current filters.',
    unavailable: 'The protected admin user directory is unavailable in this environment.',
    currentAdminTitle: 'Current admin record',
    currentAdminDescription: 'The acting ADMIN profile remains the authority anchor for every protected route and follow-up action in this panel.',
    liveGuardrailsTitle: 'Live user guardrails',
    liveGuardrails: [
      'Admin routes stay server-guarded and deny by default when session resolution is uncertain.',
      'Internal Article previews remain invisible to non-admin users and render through the shared 404 path.',
      'Role changes, moderation, and session revocation must still pass backend authorization and audit rules even when the UI is available.',
    ],
    contractsTitle: 'Backend contracts still required',
    contractsDescription: 'The frontend now consumes these contracts. Full account administration depends on the backend enforcing them with audit and self-protection rules.',
    contractItems: {
      directory: {
        title: 'User directory',
        endpoint: 'GET /api/v1/admin/users?cursor=...',
        note: 'Return bounded pages only, with minimal identity fields, role, account status, and audit-safe metadata.',
      },
      roleChange: {
        title: 'Role change',
        endpoint: 'POST /api/v1/admin/users/{user_id}/role',
        note: 'Require explicit reason, self-protection rules, and an audit record for every mutation.',
      },
      moderation: {
        title: 'Account moderation',
        endpoint: 'POST /api/v1/admin/users/{user_id}/moderation',
        note: 'Support restricted and suspended states, reversal, actor attribution, and expiration when temporary.',
      },
      revokeSessions: {
        title: 'Session revocation',
        endpoint: 'POST /api/v1/admin/users/{user_id}/sessions/revoke',
        note: 'Allow revoking all sessions or all except current, with audit and rate limiting.',
      },
    },
    pagination: {
      next: 'Next page',
      previous: 'Previous page',
    },
  },
  userDetail: {
    backToUsers: 'Back to user directory',
    loading: 'Loading protected user record…',
    unavailable: 'This user record is unavailable in the current environment.',
    notFound: 'No protected user record matched this id.',
    summaryTitle: 'Account summary',
    summaryDescription: 'Review the current role, account status, session footprint, and backend-provided protection hints before taking action.',
    capabilityFallback: 'The backend did not return explicit capability flags for this record. Server authorization remains authoritative.',
    actionFeedbackSuccess: 'Action completed.',
    roleActionTitle: 'Role change',
    roleActionDescription: 'Promote or demote this account with an explicit reason. The backend must still enforce last-admin and self-protection rules.',
    roleSelectLabel: 'Target role',
    roleReasonLabel: 'Reason',
    roleReasonPlaceholder: 'Explain why this role change is necessary',
    roleSubmit: 'Apply role change',
    moderationTitle: 'Moderation state',
    moderationDescription: 'Restrict or suspend access with a reviewable reason and optional expiration for temporary measures.',
    moderationStatusLabel: 'Target status',
    moderationReasonLabel: 'Reason',
    moderationReasonPlaceholder: 'Describe the moderation reason and next review step',
    moderationExpiresAtLabel: 'Expires at (optional)',
    moderationSubmit: 'Apply moderation',
    sessionsTitle: 'Session revocation',
    sessionsDescription: 'Use this when you need to invalidate existing sessions after suspicious activity, role changes, or credential rotation.',
    sessionsModeLabel: 'Revocation mode',
    sessionsReasonLabel: 'Reason',
    sessionsReasonPlaceholder: 'Explain why these sessions must be revoked',
    sessionsSubmit: 'Revoke sessions',
    sessionModes: {
      all: 'All sessions',
      'except-current': 'All except current',
    },
    summaryFields: {
      activeSessions: 'Active sessions',
      lastAudit: 'Last audit',
      restriction: 'Restriction',
    },
    guardedNotesTitle: 'Guarded notes',
    guardedNotes: [
      'Server-side authorization remains the source of truth for every mutation.',
      'The UI must not bypass last-admin protection or self-protection even if a button is visible.',
      'Every high-risk action should create an audit entry upstream.',
    ],
    selfRoleWarning: 'Self-demotion is intentionally blocked in the client as an extra guardrail. The backend must still enforce this.',
  },
  audit: {
    searchLabel: 'Search audit trail',
    searchPlaceholder: 'Search actor, target, or summary',
    actionFilterLabel: 'Action filter',
    applyFilters: 'Apply filters',
    clearFilters: 'Clear filters',
    actionFilters: {
      all: 'All actions',
      role_change: 'Role changes',
      moderation: 'Moderation',
      session_revoke: 'Session revocation',
      access_check: 'Access checks',
    },
    summaryCards: {
      visible: 'Visible entries',
      filtered: 'Filtered mode',
    },
    listTitle: 'Protected audit trail',
    listDescription: 'Audit entries are bounded by cursor pagination and stay hidden from public navigation and indexing.',
    empty: 'No audit entries were returned yet.',
    emptyFiltered: 'No audit entries match the current filters.',
    unavailable: 'The protected admin audit trail is unavailable in this environment.',
    actorLabel: 'Actor',
    targetLabel: 'Target',
    ipLabel: 'IP address',
    actionLabel: 'Action',
    occurredAtLabel: 'Occurred at',
    pagination: {
      next: 'Next page',
      previous: 'Previous page',
    },
  },
  access: {
    summaryTitle: 'Guardrail summary',
    summaryDescription: 'Internal surfaces are protected on the server, kept out of indexation, and denied by default whenever auth is uncertain.',
    matrixTitle: 'Route protection matrix',
    matrixDescription: 'This matrix reflects the current access policy enforced by the frontend.',
    states: {
      serverAdmin: 'Server admin check',
      featureStage: 'Feature stage gate',
      noindex: 'Noindex',
      publicWhenReleased: 'Public when released',
      disabled: 'Disabled / 404',
    },
    accessRules: {
      adminOnly: 'ADMIN only',
      articleInternal: 'ADMIN only while internal',
      articlePublic: 'Public feed and detail, authenticated owner workspace',
      unavailable: 'Unavailable',
    },
  },
  content: {
    operationsTitle: 'Content operations',
    operationsDescription: 'Use these shortcuts and policies to inspect the Article System without exposing unfinished content publicly.',
    openFeed: 'Open feed preview',
    openWorkspace: 'Open workspace',
    openEditor: 'Open editor',
    disabled: 'The Article System is off here, so content operation shortcuts stay unavailable.',
    policyTitle: 'Content safety checklist',
    policyDescription: 'These are the active guardrails that matter most for content administration today.',
    policies: {
      markdown: 'Raw HTML stays blocked in Markdown rendering.',
      uploads: 'Uploads remain restricted to signed PNG, JPEG, and WebP flows.',
      visibility: 'Private content must not leak into public routes or metadata.',
      pagination: 'Feed browsing keeps cursor pagination instead of OFFSET queries.',
    },
  },
} as const;
