export const adminWorkspaceTextPt = {
  shell: {
    badge: 'Controle ADMIN',
    title: 'Painel seguro de operações protegidas.',
    description:
      'Opere rotas protegidas, revise atividade de contas e prepare ações privilegiadas sem expor ferramentas inacabadas para visitantes comuns.',
    navigationLabel: 'Áreas admin',
    currentAdminLabel: 'Admin atual',
    featureStageLabel: 'Estágio do Article',
    featureStageStates: {
      off: 'Desligado',
      internal: 'Interno',
      public: 'Público',
    },
    serverGuardLabel: 'Modo de guarda',
    serverGuardValue: 'Negação padrão no servidor',
    recoveryTitle: 'Restaurando acesso admin…',
    recoveryDescription:
      'A sessão protegida ainda está sendo revalidada neste carregamento. Assim que o client confirmar o papel admin novamente, o painel volta sem precisar sair da rota.',
    recoveryPendingTitle: 'Sessão admin em recuperação',
    recoveryPendingDescription: 'Aguarde enquanto o acesso privilegiado é confirmado novamente.',
    recoveryDeniedTitle: 'Acesso admin não pôde ser confirmado',
    recoveryDeniedDescription:
      'O servidor não conseguiu confirmar uma sessão admin válida para este carregamento. Se a sessão realmente expirou, entre novamente; se não, volte para uma rota comum e tente abrir o painel depois que a sessão for restaurada.',
    recoveryUnavailableTitle: 'Não foi possível restaurar o acesso admin agora',
    recoveryUnavailableDescription:
      'A revalidação do painel falhou neste momento. Tente novamente ou volte para uma rota pública até a sessão estabilizar.',
    recoveryBackToSite: 'Voltar para o site',
  },
  sections: {
    overview: {
      navLabel: 'Visão geral',
      title: 'Visão geral admin',
      description: 'Sala de controle para rotas protegidas, trabalho privilegiado e próximas ações com foco em segurança.',
    },
    users: {
      navLabel: 'Usuários',
      title: 'Diretório de usuários',
      description: 'Revise contas da plataforma com filtros limitados, acesso protegido e ações posteriores auditáveis.',
    },
    audit: {
      navLabel: 'Auditoria',
      title: 'Trilha de auditoria',
      description: 'Inspecione atividade privilegiada com busca limitada, paginação por cursor e acesso negado por padrão.',
    },
    access: {
      navLabel: 'Acesso',
      title: 'Acesso e guardrails',
      description: 'Acompanhe quais rotas estão protegidas, como isso é imposto e o que está visível neste momento.',
    },
    content: {
      navLabel: 'Conteúdo',
      title: 'Operações de conteúdo',
      description: 'Opere previews de artigos, checagens de moderação e políticas de segurança de conteúdo em um só lugar.',
    },
  },
  common: {
    name: 'Nome',
    email: 'E-mail',
    role: 'Função',
    status: 'Status',
    createdAt: 'Criado em',
    updatedAt: 'Atualizado em',
    lastSeenAt: 'Último acesso',
    actions: 'Ações',
    query: 'Busca',
    sort: 'Ordenação',
    version: 'Versão',
    contract: 'Contrato',
    access: 'Acesso',
    guard: 'Proteção',
    visibility: 'Visibilidade',
    surface: 'Superfície',
    dependency: 'Dependência',
    securityNote: 'Nota de segurança',
    loading: 'Carregando…',
    unavailable: 'Indisponível neste ambiente.',
    retry: 'Tentar novamente',
  },
  overview: {
    cards: {
      adminAreas: 'Áreas admin',
      protectedRoutes: 'Rotas protegidas',
      articleMode: 'Modo do Article',
      authSource: 'Fonte de auth',
    },
    authSourceValue: 'Upstream de auth direto + fallback por token espelhado',
    quickActionsTitle: 'Ações rápidas',
    quickActionsDescription: 'Salte direto para as áreas protegidas mais úteis durante desenvolvimento, revisão e operação de contas.',
    openUsers: 'Abrir área de usuários',
    openAudit: 'Abrir auditoria',
    openAccess: 'Revisar guardrails',
    openContent: 'Abrir operações de conteúdo',
    openArticleFeed: 'Abrir feed de artigos',
    openArticleWorkspace: 'Abrir workspace de artigos',
    openArticleEditor: 'Abrir editor de artigos',
    articleUnavailable: 'O Article System está desligado neste ambiente, então as ações de preview de conteúdo ficam desabilitadas aqui.',
    readinessTitle: 'Prontidão operacional',
    readinessDescription: 'Este painel agora inclui integração segura da API admin, superfícies reais de diretório e base de auditoria. As mutações de alto risco ainda dependem da aplicação backend e de contratos auditáveis.',
  },
  users: {
    searchLabel: 'Buscar usuários',
    searchPlaceholder: 'Busque por nome, e-mail ou id do usuário',
    roleFilterLabel: 'Filtro de função',
    versionFilterLabel: 'Filtro de versão',
    statusFilterLabel: 'Filtro de status',
    sortLabel: 'Ordenação',
    applyFilters: 'Aplicar filtros',
    clearFilters: 'Limpar filtros',
    roleFilters: {
      all: 'Todas as funções',
      USER: 'Usuários',
      ADMIN: 'Admins',
    },
    statusFilters: {
      all: 'Todos os status',
      active: 'Ativo',
      restricted: 'Restrito',
      suspended: 'Suspenso',
    },
    versionFilters: {
      all: 'Todas as versões',
      legacy: 'Legado por bridge',
      'product-v1': 'Produto v1',
    },
    sortOptions: {
      'created-desc': 'Mais novos primeiro',
      'created-asc': 'Mais antigos primeiro',
      'last-seen-desc': 'Acesso recente',
      'last-seen-asc': 'Acesso menos recente',
    },
    summaryCards: {
      visible: 'Usuários visíveis',
      admins: 'Admins na página',
      legacy: 'Legado na página',
      active: 'Ativos na página',
      restricted: 'Restritos na página',
    },
    tableTitle: 'Diretório protegido de usuários',
    tableDescription: 'Este diretório é carregado pelo proxy protegido da API admin e reflete contas do produto que já foram sincronizadas para o novo modelo de autorização.',
    tableColumns: {
      user: 'Usuário',
      version: 'Versão',
      status: 'Status',
      role: 'Função',
      lastSeen: 'Último acesso',
      createdAt: 'Criado em',
    },
    openUser: 'Abrir registro',
    empty: 'Nenhum usuário foi retornado para este ambiente ainda.',
    emptyFiltered: 'Nenhum usuário combina com os filtros atuais.',
    unavailable: 'O diretório protegido de usuários admin está indisponível neste ambiente.',
    currentAdminTitle: 'Registro do admin atual',
    currentAdminDescription: 'O perfil ADMIN atuante continua sendo a âncora de autoridade para cada rota protegida e ação posterior neste painel.',
    syncTitle: 'Sync legado',
    syncDescription: 'Sincronize lotes limitados de identidades que existem só no auth para contas do produto, para que o diretório possa operá-las com segurança.',
    syncAction: 'Sincronizar próximo lote',
    syncCursorLabel: 'Próximo cursor de sync',
    syncStartCursor: 'Início do diretório',
    syncReady: 'Pronto para sincronizar desde o início do diretório do auth.',
    syncProgress: 'O próximo lote continuará a partir do último cursor retornado pelo serviço de auth.',
    syncSuccess: 'Lote do diretório sincronizado com sucesso.',
    syncUnavailable: 'O sync legado do diretório está indisponível neste ambiente.',
    syncSummary: {
      synced: 'Sincronizados no lote',
      created: 'Criados',
      updated: 'Atualizados',
    },
    productDirectoryScope: 'Este diretório lista apenas contas já respaldadas pelo produto. Identidades legadas que existem só no auth passam a aparecer aqui depois de serem sincronizadas por uma requisição protegida do produto ou pela ação protegida de sync legado abaixo.',
    liveGuardrailsTitle: 'Guardrails de usuários já ativos',
    liveGuardrails: [
      'Rotas admin continuam protegidas no servidor e negam por padrão quando a resolução da sessão fica incerta.',
      'Previews internos de Article seguem invisíveis para não-admins e renderizam pela 404 compartilhada.',
      'Mudança de papel, moderação e revogação de sessão ainda precisam passar por autorização backend e auditoria mesmo quando a UI estiver disponível.',
    ],
    contractsTitle: 'Contratos de backend ainda necessários',
    contractsDescription: 'O frontend agora consome estes contratos. A administração completa de contas depende de o backend impô-los com auditoria e regras de autoproteção.',
    contractItems: {
      directory: {
        title: 'Diretório de usuários',
        endpoint: 'GET /api/v1/admin/users?cursor=...',
        note: 'Retorne apenas páginas limitadas, com campos mínimos de identidade, papel, status da conta e metadados seguros para auditoria.',
      },
      roleChange: {
        title: 'Mudança de papel',
        endpoint: 'POST /api/v1/admin/users/{user_id}/role',
        note: 'Exige motivo explícito, regras de autoproteção e um registro de auditoria para cada mutação.',
      },
      moderation: {
        title: 'Moderação de conta',
        endpoint: 'POST /api/v1/admin/users/{user_id}/moderation',
        note: 'Precisa suportar estados restrito e suspenso, reversão, ator responsável e expiração quando temporário.',
      },
      revokeSessions: {
        title: 'Revogação de sessões',
        endpoint: 'POST /api/v1/admin/users/{user_id}/sessions/revoke',
        note: 'Deve permitir revogar todas as sessões ou todas exceto a atual, com auditoria e rate limit.',
      },
      directorySync: {
        title: 'Sync legado do diretório',
        endpoint: 'POST /api/v1/admin/users/sync-directory',
        note: 'Busca um lote limitado do diretório protegido do auth, faz upsert em product_users e registra uma entrada de auditoria para a ação de sync.',
      },
    },
    pagination: {
      next: 'Próxima página',
      previous: 'Página anterior',
    },
  },
  userDetail: {
    backToUsers: 'Voltar ao diretório de usuários',
    loading: 'Carregando registro protegido do usuário…',
    unavailable: 'Este registro de usuário está indisponível no ambiente atual.',
    notFound: 'Nenhum registro protegido corresponde a este id.',
    summaryTitle: 'Resumo da conta',
    summaryDescription: 'Revise papel atual, status da conta, sessões e hints de proteção vindos do backend antes de agir.',
    capabilityFallback: 'O backend não retornou flags explícitas de capacidade para este registro. A autorização server-side continua soberana.',
    actionFeedbackSuccess: 'Ação concluída.',
    roleActionTitle: 'Mudança de papel',
    roleActionDescription: 'Promova ou rebaixe esta conta com motivo explícito. O backend ainda deve impor proteção do último admin e autoproteção.',
    roleSelectLabel: 'Papel de destino',
    roleReasonLabel: 'Motivo',
    roleReasonPlaceholder: 'Explique por que esta mudança de papel é necessária',
    roleSubmit: 'Aplicar mudança de papel',
    moderationTitle: 'Estado de moderação',
    moderationDescription: 'Restrinja ou suspenda acesso com um motivo revisável e expiração opcional quando a medida for temporária.',
    moderationStatusLabel: 'Status de destino',
    moderationReasonLabel: 'Motivo',
    moderationReasonPlaceholder: 'Descreva o motivo da moderação e o próximo passo de revisão',
    moderationExpiresAtLabel: 'Expira em (opcional)',
    moderationSubmit: 'Aplicar moderação',
    sessionsTitle: 'Revogação de sessões',
    sessionsDescription: 'Use isto quando precisar invalidar sessões existentes após atividade suspeita, mudança de papel ou rotação de credencial.',
    sessionsModeLabel: 'Modo de revogação',
    sessionsReasonLabel: 'Motivo',
    sessionsReasonPlaceholder: 'Explique por que estas sessões precisam ser revogadas',
    sessionsSubmit: 'Revogar sessões',
    sessionModes: {
      all: 'Todas as sessões',
      'except-current': 'Todas exceto a atual',
    },
    summaryFields: {
      version: 'Versão',
      activeSessions: 'Sessões ativas',
      lastAudit: 'Última auditoria',
      restriction: 'Restrição',
    },
    guardedNotesTitle: 'Notas protegidas',
    guardedNotes: [
      'A autorização server-side continua sendo a fonte de verdade para toda mutação.',
      'A UI não pode contornar proteção do último admin nem autoproteção mesmo que um botão esteja visível.',
      'Toda ação de alto risco deve gerar uma entrada de auditoria no upstream.',
    ],
    legacyVersionNote: 'Este registro foi sincronizado pela bridge legada do auth. Ele já participa do modelo de autorização do produto, mas não nasceu como uma conta nativa do produto.',
    productVersionNote: 'Este registro está marcado como conta product-v1 e não depende mais da bridge legada para o ciclo de vida de identidade.',
    selfRoleWarning: 'O auto-rebaixamento está bloqueado no client como proteção extra. O backend ainda deve impor isso.',
  },
  audit: {
    searchLabel: 'Buscar auditoria',
    searchPlaceholder: 'Busque por ator, alvo ou resumo',
    actionFilterLabel: 'Filtro de ação',
    applyFilters: 'Aplicar filtros',
    clearFilters: 'Limpar filtros',
    actionFilters: {
      all: 'Todas as ações',
      role_change: 'Mudanças de papel',
      moderation: 'Moderação',
      session_revoke: 'Revogação de sessão',
      directory_sync: 'Sync de diretório',
      access_check: 'Checagens de acesso',
    },
    summaryCards: {
      visible: 'Entradas visíveis',
      filtered: 'Modo filtrado',
    },
    listTitle: 'Trilha protegida de auditoria',
    listDescription: 'As entradas de auditoria são limitadas por paginação por cursor e continuam fora da navegação pública e da indexação.',
    empty: 'Nenhuma entrada de auditoria foi retornada ainda.',
    emptyFiltered: 'Nenhuma entrada de auditoria combina com os filtros atuais.',
    unavailable: 'A trilha protegida de auditoria admin está indisponível neste ambiente.',
    actorLabel: 'Ator',
    targetLabel: 'Alvo',
    ipLabel: 'IP',
    actionLabel: 'Ação',
    occurredAtLabel: 'Ocorrido em',
    pagination: {
      next: 'Próxima página',
      previous: 'Página anterior',
    },
  },
  access: {
    summaryTitle: 'Resumo dos guardrails',
    summaryDescription: 'Superfícies internas são protegidas no servidor, ficam fora de indexação e são negadas por padrão sempre que a auth estiver incerta.',
    matrixTitle: 'Matriz de proteção de rotas',
    matrixDescription: 'Esta matriz reflete a política de acesso atualmente imposta pelo frontend.',
    states: {
      serverAdmin: 'Checagem admin no servidor',
      featureStage: 'Gate por estágio da feature',
      noindex: 'Noindex',
      publicWhenReleased: 'Público quando liberado',
      disabled: 'Desligado / 404',
    },
    accessRules: {
      adminOnly: 'Somente ADMIN',
      articleInternal: 'Somente ADMIN enquanto estiver interno',
      articlePublic: 'Feed e detalhe públicos, workspace do dono autenticado',
      unavailable: 'Indisponível',
    },
  },
  content: {
    operationsTitle: 'Operações de conteúdo',
    operationsDescription: 'Use estes atalhos e políticas para inspecionar o Article System sem expor conteúdo inacabado publicamente.',
    openFeed: 'Abrir preview do feed',
    openWorkspace: 'Abrir workspace',
    openEditor: 'Abrir editor',
    disabled: 'O Article System está desligado aqui, então os atalhos de operação de conteúdo ficam indisponíveis.',
    policyTitle: 'Checklist de segurança de conteúdo',
    policyDescription: 'Estes são os guardrails ativos que mais importam para a administração de conteúdo hoje.',
    policies: {
      markdown: 'HTML bruto continua bloqueado na renderização de Markdown.',
      uploads: 'Uploads seguem restritos a fluxos assinados de PNG, JPEG e WebP.',
      visibility: 'Conteúdo privado não pode vazar para rotas públicas nem metadata.',
      pagination: 'A navegação do feed mantém paginação por cursor em vez de OFFSET.',
    },
  },
} as const;
