export const adminWorkspaceTextEn = {
  shell: {
    badge: 'ADMIN control',
    title: 'Operations panel built for guarded work.',
    description:
      'Review protected areas, inspect content workflows, and prepare user management without exposing unfinished tooling to regular visitors.',
    navigationLabel: 'Admin areas',
    currentAdminLabel: 'Current admin',
    featureStageLabel: 'Article stage',
    featureStageStates: {
      off: 'Off',
      internal: 'Internal',
      public: 'Public',
    },
    serverGuardLabel: 'Guard mode',
    serverGuardValue: 'Server-side deny by default',
  },
  sections: {
    overview: {
      navLabel: 'Overview',
      title: 'Admin overview',
      description: 'High-level control room for guarded routes, feature visibility, and next operational actions.',
    },
    users: {
      navLabel: 'Users',
      title: 'User management',
      description: 'Structure the most common account administration workflows with safe status reporting.',
    },
    access: {
      navLabel: 'Access',
      title: 'Access and guardrails',
      description: 'Track which routes are protected, how they are enforced, and what is currently visible.',
    },
    content: {
      navLabel: 'Content',
      title: 'Content operations',
      description: 'Operate article previews, moderation-oriented checks, and content safety policies from one place.',
    },
  },
  common: {
    name: 'Name',
    email: 'Email',
    role: 'Role',
    contract: 'Contract',
    status: 'Status',
    access: 'Access',
    guard: 'Guard',
    visibility: 'Visibility',
    surface: 'Surface',
    dependency: 'Dependency',
    securityNote: 'Security note',
  },
  overview: {
    cards: {
      adminAreas: 'Admin areas',
      protectedRoutes: 'Protected routes',
      articleMode: 'Article mode',
      authSource: 'Auth source',
    },
    authSourceValue: 'Direct auth upstream + mirrored token fallback',
    quickActionsTitle: 'Quick actions',
    quickActionsDescription: 'Jump directly to the protected areas you are most likely to inspect during development and moderation work.',
    openUsers: 'Open users area',
    openAccess: 'Review guardrails',
    openContent: 'Open content ops',
    openArticleFeed: 'Open article feed',
    openArticleWorkspace: 'Open article workspace',
    openArticleEditor: 'Open article editor',
    articleUnavailable: 'The Article System is off in this environment, so content preview actions stay disabled here.',
    readinessTitle: 'Operational readiness',
    readinessDescription: 'This panel is ready for secure internal use now. User mutations are intentionally waiting for dedicated backend admin endpoints.',
  },
  users: {
    searchLabel: 'Search capabilities',
    searchPlaceholder: 'Search capability, action, or dependency',
    applyFilters: 'Apply filters',
    clearFilters: 'Clear filters',
    filterStatusLabel: 'Status filter',
    filterTrackLabel: 'Operations track',
    summaryCards: {
      visible: 'Visible operations',
      available: 'Ready now',
      guarded: 'Guarded now',
      planned: 'Waiting on backend',
    },
    currentAdminTitle: 'Current admin record',
    currentAdminDescription: 'This workspace uses the acting ADMIN profile as the live authority anchor for every protected route.',
    liveGuardrailsTitle: 'Live user guardrails',
    liveGuardrails: [
      'Admin routes stay server-guarded and deny by default when session resolution is uncertain.',
      'Internal Article previews remain invisible to non-admin users and render through the shared 404 path.',
      'Role changes and moderation actions are intentionally blocked until dedicated backend audit contracts exist.',
    ],
    capabilitiesTitle: 'Common admin user operations',
    capabilitiesDescription: 'Use this view to separate what is already live, what is safely guarded, and what still needs backend authority before release.',
    empty: 'No admin capability matched this search.',
    emptyFiltered: 'No admin operation matches the current filters.',
    statuses: {
      available: 'Ready now',
      planned: 'Needs backend',
      guarded: 'Guarded foundation',
    },
    statusFilters: {
      all: 'All statuses',
      available: 'Ready now',
      guarded: 'Guarded',
      planned: 'Needs backend',
    },
    trackFilters: {
      all: 'All tracks',
      session: 'Session',
      access: 'Access',
      directory: 'Directory',
      roles: 'Roles',
      moderation: 'Moderation',
      audit: 'Audit',
    },
    capabilityItems: {
      resolveSession: {
        title: 'Resolve current admin session',
        description: 'Server-side access already confirms that the acting user is ADMIN before rendering the panel.',
        dependency: 'Direct auth upstream validation',
        securityNote: 'This is live and deny-by-default when auth is uncertain.',
        contract: 'GET /auth/profile',
      },
      openProtectedAreas: {
        title: 'Open admin-only areas safely',
        description: 'Professional admin panels need clear separation between public and internal routes.',
        dependency: 'Current admin route guards',
        securityNote: 'Protected surfaces render 404 for non-admins.',
        contract: 'GET /[locale]/admin/*',
      },
      listUsers: {
        title: 'List platform users',
        description: 'A dedicated user directory should expose pagination, filters, and minimal identity fields only.',
        dependency: 'Backend admin users endpoint',
        securityNote: 'Must never trust client-side role changes or unbounded queries.',
        contract: 'GET /api/v1/admin/users?cursor=...',
      },
      changeRole: {
        title: 'Change user role',
        description: 'Promote or demote users through audited admin actions with explicit confirmation.',
        dependency: 'Backend role mutation endpoint',
        securityNote: 'Needs server-side authorization, audit trail, and self-protection rules.',
        contract: 'POST /api/v1/admin/users/{user_id}/role',
      },
      suspendAccount: {
        title: 'Suspend or restrict accounts',
        description: 'Common admin workflows usually include temporary account restrictions and recovery steps.',
        dependency: 'Backend moderation endpoints',
        securityNote: 'Needs clear appeal and recovery logic before release.',
        contract: 'POST /api/v1/admin/users/{user_id}/moderation',
      },
      auditTrail: {
        title: 'Review admin audit trail',
        description: 'Professional admin panels need bounded history for role changes, moderation, and protected access decisions.',
        dependency: 'Backend audit stream endpoint',
        securityNote: 'Logs must be append-only, filterable, and scoped away from public traffic.',
        contract: 'GET /api/v1/admin/audit?cursor=...',
      },
    },
    contractsTitle: 'Backend contracts to unlock',
    contractsDescription: 'These are the bounded admin endpoints worth building next if you want this panel to move from guarded planning to live account operations.',
    contractItems: {
      directory: {
        title: 'User directory',
        endpoint: 'GET /api/v1/admin/users?cursor=...',
        note: 'Return minimal identity fields, role, status, and bounded filters. No unbounded scans.',
      },
      roleChange: {
        title: 'Role changes',
        endpoint: 'POST /api/v1/admin/users/{user_id}/role',
        note: 'Require explicit confirmation, self-protection rules, and an audit record for every mutation.',
      },
      moderation: {
        title: 'Account restriction',
        endpoint: 'POST /api/v1/admin/users/{user_id}/moderation',
        note: 'Support temporary restrictions, reversal, actor attribution, and reason capture.',
      },
      audit: {
        title: 'Audit trail',
        endpoint: 'GET /api/v1/admin/audit?cursor=...',
        note: 'Expose append-only operational history with cursor pagination and role-scoped access.',
      },
    },
  },
  access: {
    summaryTitle: 'Guardrail summary',
    summaryDescription: 'Internal surfaces are protected on the server, kept out of indexation, and denied by default whenever auth is uncertain.',
    matrixTitle: 'Route protection matrix',
    matrixDescription: 'This matrix reflects the current access policy enforced by the frontend.',
    states: {
      serverAdmin: 'Server admin check',
      featureStage: 'Feature stage gate',
      noindex: 'Noindex',
      publicWhenReleased: 'Public when released',
      disabled: 'Disabled / 404',
    },
    accessRules: {
      adminOnly: 'ADMIN only',
      articleInternal: 'ADMIN only while internal',
      articlePublic: 'Public feed and detail, authenticated owner workspace',
      unavailable: 'Unavailable',
    },
  },
  content: {
    operationsTitle: 'Content operations',
    operationsDescription: 'Use these shortcuts and policies to inspect the Article System without exposing unfinished content publicly.',
    openFeed: 'Open feed preview',
    openWorkspace: 'Open workspace',
    openEditor: 'Open editor',
    disabled: 'The Article System is off here, so content operation shortcuts stay unavailable.',
    policyTitle: 'Content safety checklist',
    policyDescription: 'These are the active guardrails that matter most for content administration today.',
    policies: {
      markdown: 'Raw HTML stays blocked in Markdown rendering.',
      uploads: 'Uploads remain restricted to signed PNG, JPEG, and WebP flows.',
      visibility: 'Private content must not leak into public routes or metadata.',
      pagination: 'Feed browsing keeps cursor pagination instead of OFFSET queries.',
    },
  },
} as const;
