export const articleEditorTextPt = {
  eyebrow: 'Editor de Artigos',
  title: 'Escreva e refine um artigo.',
  description:
    'Escreva em markdown, ajuste o resumo, escolha a visibilidade e salve um rascunho sem expor isso publicamente ainda.',
  internalBadge: 'Preview Interno',
  form: {
    titleLabel: 'Título',
    titlePlaceholder: 'Orbitais atômicos sem intimidação',
    excerptLabel: 'Resumo',
    excerptPlaceholder: 'Resuma o assunto do artigo em uma ou duas frases.',
    coverImageLabel: 'Imagem de capa',
    coverImageHint:
      'Opcional. Envie uma imagem de capa para destacar o artigo nos cards do feed e no cabeçalho do detalhe.',
    coverImageEmpty: 'Nenhuma imagem de capa foi selecionada ainda.',
    markdownLabel: 'Markdown',
    markdownPlaceholder: '# Comece aqui\n\nEscreva seu artigo em Markdown.',
    visibilityLabel: 'Visibilidade',
    visibilityPublic: 'Público',
    visibilityPrivate: 'Privado',
    hashtagsLabel: 'Hashtags',
    hashtagsPlaceholder: '#quimica, orbitais, estudo',
    hashtagsHint: 'Use vírgulas ou espaços. O editor mantém até 10 hashtags normalizadas.',
    imageUploadLabel: 'Upload de imagem',
    imageUploadHint:
      'JPEG, PNG ou WebP até 5MB. O editor envia direto e insere a sintaxe markdown da imagem.',
    slugPreviewLabel: 'Preview do slug',
    previewLabel: 'Preview ao vivo',
  },
  actions: {
    saveDraft: 'Salvar rascunho',
    savingDraft: 'Salvando rascunho...',
    uploadImage: 'Enviar imagem',
    uploadingImage: 'Enviando imagem...',
    uploadCoverImage: 'Enviar capa',
    uploadingCoverImage: 'Enviando capa...',
    clearCoverImage: 'Remover capa',
    publish: 'Publicar',
    publishing: 'Publicando...',
    unpublish: 'Despublicar',
    unpublishing: 'Despublicando...',
    openWorkspace: 'Abrir meus artigos',
  },
  notices: {
    signInRequired: 'Entre para criar e salvar rascunhos de artigos.',
    loadingArticle: 'Carregando seu rascunho de artigo...',
    loadFailed: 'Não foi possível carregar este artigo agora.',
    loadFailedNetwork: 'Não foi possível carregar este artigo. Verifique sua conexão e tente de novo.',
    loadForbidden: 'Você não tem acesso a este artigo.',
    loadNotFound: 'Não foi possível encontrar este rascunho de artigo.',
    unavailable: 'O editor de artigos não está disponível agora.',
    saveSucceeded: 'Rascunho salvo com sucesso.',
    saveFailed: 'Não foi possível salvar seu rascunho agora.',
    saveFailedNetwork: 'Não foi possível salvar seu rascunho. Verifique sua conexão e tente de novo.',
    uploadSucceeded: 'Imagem enviada e markdown atualizado.',
    coverUploadSucceeded: 'Imagem de capa enviada com sucesso.',
    coverCleared: 'Imagem de capa removida deste rascunho.',
    uploadFailed: 'Não foi possível enviar esta imagem agora.',
    uploadFailedNetwork:
      'Não foi possível enviar esta imagem. Verifique sua conexão e tente de novo.',
    uploadInvalidType: 'Somente imagens JPEG, PNG e WebP são permitidas.',
    uploadTooLarge: 'Esta imagem é grande demais. O limite é 5MB.',
    autosaveFailed: 'Não foi possível salvar seu rascunho automaticamente agora.',
    autosaveFailedNetwork:
      'Não foi possível salvar seu rascunho automaticamente. Verifique sua conexão e tente de novo.',
    publishSucceeded: 'Artigo publicado com sucesso.',
    publishFailed: 'Não foi possível publicar este artigo agora.',
    publishFailedNetwork:
      'Não foi possível publicar este artigo. Verifique sua conexão e tente de novo.',
    unpublishSucceeded: 'Artigo voltou para rascunho com sucesso.',
    unpublishFailed: 'Não foi possível despublicar este artigo agora.',
    unpublishFailedNetwork:
      'Não foi possível despublicar este artigo. Verifique sua conexão e tente de novo.',
    saveBeforePublish: 'Salve o rascunho pelo menos uma vez antes de publicar.',
    publishNeedsTitle: 'Adicione um título antes de publicar.',
    publishNeedsMarkdown: 'Adicione conteúdo em markdown antes de publicar.',
    emptyPreview: 'Comece a escrever em Markdown para ver o preview aqui.',
  },
  meta: {
    currentStatus: 'Status atual',
    currentSlug: 'Slug atual',
    lastSaved: 'Último salvamento',
    publishedAt: 'Publicado em',
    autosaveStatus: 'Auto-save',
    autosaveIdle: 'Sem alterações pendentes',
    autosavePending: 'Alterações pendentes',
    autosaveSaving: 'Salvando automaticamente...',
    autosaveSaved: 'Salvo automaticamente',
    autosaveDisabledPublished: 'Desativado enquanto o artigo estiver publicado',
    unsaved: 'Ainda não salvo',
    draft: 'Rascunho',
    published: 'Publicado',
    archived: 'Arquivado',
  },
} as const;
