export const articleEditorTextEn = {
  eyebrow: 'Article Editor',
  title: 'Draft and refine an article.',
  description:
    'Write markdown, shape the excerpt, choose visibility, and save a draft without exposing it publicly yet.',
  internalBadge: 'Internal Preview',
  form: {
    titleLabel: 'Title',
    titlePlaceholder: 'Atomic orbitals without the intimidation',
    excerptLabel: 'Excerpt',
    excerptPlaceholder: 'Summarize what the article is about in one or two sentences.',
    coverImageLabel: 'Cover image',
    coverImageHint:
      'Optional. Upload a cover image to highlight the article in feed cards and the article detail header.',
    coverImageEmpty: 'No cover image selected yet.',
    markdownLabel: 'Markdown source',
    markdownToolsLabel: 'Markdown tools',
    markdownPlaceholder: '# Start here\n\nWrite your article in Markdown.',
    visibilityLabel: 'Visibility',
    visibilityPublic: 'Public',
    visibilityPrivate: 'Private',
    hashtagsLabel: 'Hashtags',
    hashtagsPlaceholder: '#chemistry, orbitals, learning',
    hashtagsHint: 'Use commas or spaces. The editor keeps up to 10 normalized hashtags.',
    imageUploadLabel: 'Image upload',
    imageUploadHint:
      'JPEG, PNG, or WebP up to 5MB. The editor uploads directly and inserts markdown image syntax.',
    slugPreviewLabel: 'Slug preview',
    previewLabel: 'Live preview',
  },
  actions: {
    saveDraft: 'Save draft',
    savingDraft: 'Saving draft...',
    restoreRecovery: 'Restore draft',
    dismissRecovery: 'Dismiss recovery',
    uploadImage: 'Upload image',
    uploadingImage: 'Uploading image...',
    uploadCoverImage: 'Upload cover',
    uploadingCoverImage: 'Uploading cover...',
    clearCoverImage: 'Remove cover',
    publish: 'Publish',
    publishing: 'Publishing...',
    unpublish: 'Unpublish',
    unpublishing: 'Unpublishing...',
    deleteArticle: 'Delete article',
    deletingArticle: 'Deleting article...',
    confirmDelete: 'Confirm delete',
    cancelDelete: 'Keep article',
    openWorkspace: 'Open my articles',
  },
  notices: {
    signInRequired: 'Sign in to create and save article drafts.',
    loadingArticle: 'Loading your article draft...',
    loadFailed: 'We could not load this article right now.',
    loadFailedNetwork: 'We could not load this article. Check your connection and try again.',
    loadForbidden: 'You do not have access to this article.',
    loadNotFound: 'We could not find this article draft.',
    unavailable: 'The article editor is not available right now.',
    saveSucceeded: 'Draft saved successfully.',
    saveFailed: 'We could not save your draft right now.',
    saveFailedNetwork: 'We could not save your draft. Check your connection and try again.',
    uploadSucceeded: 'Image uploaded and markdown updated.',
    coverUploadSucceeded: 'Cover image uploaded successfully.',
    coverCleared: 'Cover image removed from this draft.',
    uploadFailed: 'We could not upload this image right now.',
    uploadUnavailable:
      'Image uploads are not available in this environment yet. The editor still works, but media depends on the storage service.',
    uploadFailedNetwork: 'We could not upload this image. Check your connection and try again.',
    uploadInvalidType: 'Only JPEG, PNG, and WebP images are allowed.',
    uploadTooLarge: 'This image is too large. The limit is 5MB.',
    autosaveFailed: 'We could not auto-save your draft right now.',
    autosaveFailedNetwork:
      'We could not auto-save your draft. Check your connection and try again.',
    recoveryAvailable:
      'We found a local draft recovery snapshot for this editor. Restore it if you want to continue from the last unsaved changes.',
    recoveryRestored: 'Recovered local draft changes into the editor.',
    recoveryDiscarded: 'Discarded the local recovery snapshot for this editor.',
    publishSucceeded: 'Article published successfully.',
    publishFailed: 'We could not publish this article right now.',
    publishFailedNetwork: 'We could not publish this article. Check your connection and try again.',
    unpublishSucceeded: 'Article moved back to draft successfully.',
    unpublishArchivedSucceeded: 'Article archived successfully.',
    unpublishFailed: 'We could not unpublish this article right now.',
    unpublishFailedNetwork:
      'We could not unpublish this article. Check your connection and try again.',
    deleteConfirmDraft:
      'Delete this draft from your workspace. You will need to create it again if you want to continue later.',
    deleteConfirmPublished:
      'Delete this article. It will stop appearing in your workspace and it will no longer be publicly available.',
    deleteFailed: 'We could not delete this article right now.',
    deleteFailedNetwork: 'We could not delete this article. Check your connection and try again.',
    saveBeforePublish: 'Save the draft once before publishing it.',
    publishNeedsTitle: 'Add a title before publishing.',
    publishNeedsMarkdown: 'Add markdown content before publishing.',
    emptyPreview: 'Start writing in Markdown to see the preview here.',
  },
  meta: {
    currentStatus: 'Current status',
    currentSlug: 'Current slug',
    lastSaved: 'Last saved',
    publishedAt: 'Published at',
    recoverySavedAt: 'Recovery saved at',
    autosaveStatus: 'Auto-save',
    autosaveIdle: 'Up to date',
    autosavePending: 'Pending changes',
    autosaveSaving: 'Saving automatically...',
    autosaveSaved: 'Saved automatically',
    autosaveDisabledPublished: 'Disabled while article is published',
    unsaved: 'Not saved yet',
    draft: 'Draft',
    published: 'Published',
    archived: 'Archived',
  },
} as const;
