export const articleEditorTextEn = {
  eyebrow: 'Article Editor',
  title: 'Draft and refine an article.',
  description:
    'Write markdown, shape the excerpt, choose visibility, and save a draft without exposing it publicly yet.',
  internalBadge: 'Internal Preview',
  form: {
    titleLabel: 'Title',
    titlePlaceholder: 'Atomic orbitals without the intimidation',
    excerptLabel: 'Excerpt',
    excerptPlaceholder: 'Summarize what the article is about in one or two sentences.',
    markdownLabel: 'Markdown source',
    markdownPlaceholder: '# Start here\n\nWrite your article in Markdown.',
    visibilityLabel: 'Visibility',
    visibilityPublic: 'Public',
    visibilityPrivate: 'Private',
    hashtagsLabel: 'Hashtags',
    hashtagsPlaceholder: '#chemistry, orbitals, learning',
    hashtagsHint: 'Use commas or spaces. The editor keeps up to 10 normalized hashtags.',
    slugPreviewLabel: 'Slug preview',
    previewLabel: 'Live preview',
  },
  actions: {
    saveDraft: 'Save draft',
    savingDraft: 'Saving draft...',
    publish: 'Publish',
    publishing: 'Publishing...',
    unpublish: 'Unpublish',
    unpublishing: 'Unpublishing...',
    openWorkspace: 'Open my articles',
  },
  notices: {
    signInRequired: 'Sign in to create and save article drafts.',
    loadingArticle: 'Loading your article draft...',
    loadFailed: 'We could not load this article right now.',
    loadFailedNetwork: 'We could not load this article. Check your connection and try again.',
    loadForbidden: 'You do not have access to this article.',
    loadNotFound: 'We could not find this article draft.',
    unavailable: 'The article editor is not available right now.',
    saveSucceeded: 'Draft saved successfully.',
    saveFailed: 'We could not save your draft right now.',
    saveFailedNetwork: 'We could not save your draft. Check your connection and try again.',
    publishSucceeded: 'Article published successfully.',
    publishFailed: 'We could not publish this article right now.',
    publishFailedNetwork: 'We could not publish this article. Check your connection and try again.',
    unpublishSucceeded: 'Article moved back to draft successfully.',
    unpublishFailed: 'We could not unpublish this article right now.',
    unpublishFailedNetwork:
      'We could not unpublish this article. Check your connection and try again.',
    saveBeforePublish: 'Save the draft once before publishing it.',
    publishNeedsTitle: 'Add a title before publishing.',
    publishNeedsMarkdown: 'Add markdown content before publishing.',
    emptyPreview: 'Start writing in Markdown to see the preview here.',
  },
  meta: {
    currentStatus: 'Current status',
    currentSlug: 'Current slug',
    lastSaved: 'Last saved',
    publishedAt: 'Published at',
    unsaved: 'Not saved yet',
    draft: 'Draft',
    published: 'Published',
    archived: 'Archived',
  },
} as const;
