export const chemistryBalanceTextEn = {
  common: {
    yes: 'Yes',
    no: 'No',
    unknown: 'Unknown',
    notAvailable: 'N/A',
    balanced: 'Balanced',
    recent: 'Recent',
    unchanged: 'unchanged',
    warnings: {
      warning: 'Warning',
      info: 'Info',
    },
    reactionTypes: {
      'combustion-like': 'Combustion-like',
      synthesis: 'Synthesis',
      decomposition: 'Decomposition',
      exchange: 'Exchange',
      unknown: 'Unknown',
    },
  },
  locale: {
    label: 'Language',
    options: {
      'en-US': 'English',
      'pt-BR': 'Português',
    },
  },
  workspace: {
    eyebrow: 'Chemistry',
    title: 'Balance Equation',
    description: 'Paste an equation to balance it locally.',
    equationLabel: 'Equation',
    equationPlaceholder: 'H2 + O2 -> H2O',
    submit: 'Balance',
    clear: 'Clear',
    resultEyebrow: 'Result',
    resultTitle: 'Balanced Equation',
    formattedLabel: 'Formatted',
    termsLabel: 'Terms',
    elementsLabel: 'Elements',
    vectorLabel: 'Vector',
    failurePrefix: 'The equation could not be balanced at the local',
    failureSuffix: 'stage.',
  },
  comparison: {
    eyebrow: 'Comparison',
    title: 'Input vs Balanced',
    unavailable: 'Balance an equation to compare it.',
    originalLabel: 'Original',
    balancedLabel: 'Balanced',
    reactantLabel: 'reactant',
    productLabel: 'product',
  },
  analysis: {
    eyebrow: 'Check',
    title: 'Quick Analysis',
    noResult: 'Available after a successful balance.',
    typeLabel: 'Type',
    scoreLabel: 'Score',
    plausibilityLabel: 'Plausibility',
    plausible: 'Looks good',
    needsReview: 'Check manually',
    noNotices: 'No extra notes.',
    metadata: {
      loading: 'Loading element details.',
      ready: 'Using extra element details.',
      unavailable: 'Using local checks only.',
      inactive: 'Using local checks.',
    },
  },
  engine: {
    eyebrow: 'Optional',
    title: 'Extra Check',
    description: '',
    toggleLabel: 'Server',
    retry: 'Retry check',
    off: 'Extra check is off.',
    idle: 'Balance again to request the extra check.',
    loadingPrefix: 'Checking',
    failedTitle: 'Extra check did not complete.',
    classificationLabel: 'Classification',
    scoreLabel: 'Score',
    validLabel: 'Valid',
    noNotices: 'No extra notes from the server.',
  },
  analysisComparison: {
    eyebrow: 'Comparison',
    title: 'Local vs Remote',
    unavailable: 'Available when both checks finish.',
    description: '',
    localLabel: 'Local',
    remoteLabel: 'Remote',
    plausibleLabel: 'Plausible',
    classificationLabel: 'Classification',
    confidenceAlignmentLabel: 'Confidence Alignment',
    aligned: 'Aligned',
    partial: 'Partial',
    different: 'Different',
    deltaPrefix: 'Delta:',
    remoteValidPrefix: 'Valid:',
    confidenceSentencePrefix: 'Local plausibility is',
    confidenceSentenceMiddle: 'while the remote engine validity is',
    positive: 'positive',
    cautious: 'cautious',
  },
  history: {
    eyebrow: 'History',
    title: 'Recent Equations',
    clear: 'Clear history',
    empty: 'Your recent equations will appear here.',
    localFailureSummary: 'The equation could not be balanced locally.',
    locale: 'en-US',
  },
  examples: {
    eyebrow: 'Examples',
    title: 'Try an Example',
    description: '',
    use: 'Use',
    categories: {
      combustion: 'Combustion',
      synthesis: 'Synthesis',
      decomposition: 'Decomposition',
      ionic: 'Ionic',
    },
    items: {
      methaneCombustion: {
        title: 'Methane combustion',
        description: 'A hydrocarbon burns in oxygen to form carbon dioxide and water.',
      },
      waterFormation: {
        title: 'Water formation',
        description: 'Two simple reactants combine into a single product family.',
      },
      ironOxideFormation: {
        title: 'Iron oxide formation',
        description: 'Metal oxidation is a good example of coefficient growth during balancing.',
      },
      calciumCarbonateBreakdown: {
        title: 'Calcium carbonate breakdown',
        description: 'A single reactant decomposes into two simpler products.',
      },
      sodiumChlorideFormation: {
        title: 'Sodium chloride formation',
        description: 'A small ionic example that also exercises explicit charge handling.',
      },
    },
  },
  pipeline: {
    eyebrow: 'Pipeline',
    title: 'Local Stages',
    steps: [
      {
        title: '1. Equation parse',
        description:
          'separates arrow, terms, coefficients, phases, and structural notation.',
      },
      {
        title: '2. Reaction creation',
        description: 'converts terms into structured participants with parsed formulas.',
      },
      {
        title: '3. Matrix balancing',
        description:
          'builds the stoichiometric matrix, solves the null-space, and normalizes coefficients.',
      },
      {
        title: '4. Heuristic analysis',
        description:
          'applies lightweight local rules and optionally enriches them with Element DB metadata.',
      },
      {
        title: '5. Deterministic formatting',
        description: 'returns a stable text result for display.',
      },
    ],
  },
} as const;
