export const chemistryBalanceTextPt = {
  common: {
    yes: 'Sim',
    no: 'Não',
    unknown: 'Desconhecido',
    notAvailable: 'N/D',
    balanced: 'Balanceada',
    recent: 'Recente',
    unchanged: 'sem mudança',
    warnings: {
      warning: 'Aviso',
      info: 'Informação',
    },
    reactionTypes: {
      'combustion-like': 'Semelhante à combustão',
      synthesis: 'Síntese',
      decomposition: 'Decomposição',
      exchange: 'Troca',
      unknown: 'Desconhecido',
    },
  },
  locale: {
    label: 'Idioma',
    options: {
      'en-US': 'English',
      'pt-BR': 'Português',
    },
  },
  workspace: {
    eyebrow: 'Química',
    title: 'Balancear Equação',
    description: 'Cole uma equação para balanceá-la localmente.',
    equationLabel: 'Equação',
    equationPlaceholder: 'H2 + O2 -> H2O',
    submit: 'Balancear',
    clear: 'Limpar',
    resultEyebrow: 'Resultado',
    resultTitle: 'Equação Balanceada',
    formattedLabel: 'Formatada',
    termsLabel: 'Termos',
    elementsLabel: 'Elementos',
    vectorLabel: 'Vetor',
    failurePrefix: 'A equação não pôde ser balanceada na etapa local de',
    failureSuffix: '.',
  },
  comparison: {
    eyebrow: 'Comparação',
    title: 'Entrada vs Balanceada',
    unavailable: 'Balanceie uma equação para compará-la.',
    originalLabel: 'Original',
    balancedLabel: 'Balanceada',
    reactantLabel: 'reagente',
    productLabel: 'produto',
  },
  analysis: {
    eyebrow: 'Verificação',
    title: 'Análise Rápida',
    noResult: 'Disponível após um balanceamento bem-sucedido.',
    typeLabel: 'Tipo',
    scoreLabel: 'Pontuação',
    plausibilityLabel: 'Plausibilidade',
    plausible: 'Parece boa',
    needsReview: 'Revise manualmente',
    noNotices: 'Sem observações extras.',
    metadata: {
      loading: 'Carregando detalhes dos elementos.',
      ready: 'Usando detalhes extras dos elementos.',
      unavailable: 'Usando apenas verificações locais.',
      inactive: 'Usando verificações locais.',
    },
  },
  engine: {
    eyebrow: 'Opcional',
    title: 'Checagem Extra',
    description: '',
    toggleLabel: 'Servidor',
    retry: 'Tentar novamente',
    off: 'A checagem extra está desativada.',
    idle: 'Balanceie de novo para pedir a checagem extra.',
    loadingPrefix: 'Verificando',
    failedTitle: 'A checagem extra não foi concluída.',
    classificationLabel: 'Classificação',
    scoreLabel: 'Pontuação',
    validLabel: 'Válida',
    noNotices: 'Sem observações extras do servidor.',
    errorMessages: {
      'network-error': 'Não conseguimos acessar a checagem extra agora.',
      unauthorized: 'A checagem extra precisa de uma sessão válida.',
      unavailable: 'A checagem extra está indisponível agora.',
      'invalid-response': 'A checagem extra respondeu de forma inválida.',
      'unknown-error': 'A checagem extra não pôde ser concluída.',
    },
  },
  analysisComparison: {
    eyebrow: 'Comparação',
    title: 'Local vs Remoto',
    unavailable: 'Disponível quando as duas verificações terminarem.',
    description: '',
    localLabel: 'Local',
    remoteLabel: 'Remoto',
    plausibleLabel: 'Plausível',
    classificationLabel: 'Classificação',
    confidenceAlignmentLabel: 'Alinhamento de Confiança',
    aligned: 'Alinhado',
    partial: 'Parcial',
    different: 'Diferente',
    deltaPrefix: 'Diferença:',
    remoteValidPrefix: 'Válida:',
    confidenceSentencePrefix: 'A plausibilidade local é',
    confidenceSentenceMiddle: 'enquanto a validade da engine remota é',
    positive: 'positiva',
    cautious: 'cautelosa',
  },
  history: {
    eyebrow: 'Histórico',
    title: 'Equações Recentes',
    clear: 'Limpar histórico',
    empty: 'Suas equações recentes vão aparecer aqui.',
    localFailureSummary: 'A equação não pôde ser balanceada localmente.',
    locale: 'pt-BR',
  },
  examples: {
    eyebrow: 'Exemplos',
    title: 'Testar um Exemplo',
    description: '',
    use: 'Usar',
    categories: {
      combustion: 'Combustão',
      synthesis: 'Síntese',
      decomposition: 'Decomposição',
      ionic: 'Iônica',
    },
    items: {
      methaneCombustion: {
        title: 'Combustão do metano',
        description: 'Um hidrocarboneto reage com oxigênio para formar dióxido de carbono e água.',
      },
      waterFormation: {
        title: 'Formação da água',
        description: 'Dois reagentes simples se combinam para formar uma única família de produto.',
      },
      ironOxideFormation: {
        title: 'Formação do óxido de ferro',
        description: 'A oxidação de metais é um bom exemplo de crescimento de coeficientes durante o balanceamento.',
      },
      calciumCarbonateBreakdown: {
        title: 'Decomposição do carbonato de cálcio',
        description: 'Um único reagente se decompõe em dois produtos mais simples.',
      },
      sodiumChlorideFormation: {
        title: 'Formação do cloreto de sódio',
        description: 'Um pequeno exemplo iônico que também exercita o tratamento de cargas explícitas.',
      },
    },
  },
  pipeline: {
    eyebrow: 'Pipeline',
    title: 'Etapas Locais',
    steps: [
      {
        title: '1. Parsing da equação',
        description:
          'separa seta, termos, coeficientes, fases e notação estrutural.',
      },
      {
        title: '2. Criação da reação',
        description: 'converte os termos em participantes estruturados com fórmulas parseadas.',
      },
      {
        title: '3. Balanceamento matricial',
        description:
          'monta a matriz estequiométrica, resolve o espaço nulo e normaliza os coeficientes.',
      },
      {
        title: '4. Análise heurística',
        description:
          'aplica regras locais leves e opcionalmente enriquece com metadados do banco de elementos.',
      },
      {
        title: '5. Formatação determinística',
        description: 'retorna um resultado textual estável para exibição.',
      },
    ],
  },
} as const;
