export const authTextEn = {
  common: {
    close: 'Close',
    tryAgain: 'Try again',
    openLogin: 'Open login',
  },
  login: {
    eyebrow: 'Welcome back',
    title: 'Login',
    subtitle: 'Sign in to save your work and keep your chemistry data in sync.',
    submit: 'Sign in',
    submitting: 'Signing in...',
    fallbackError: 'Could not sign in right now.',
    switchPrompt: 'Need an account?',
    switchAction: 'Register here',
  },
  register: {
    eyebrow: 'Get started',
    title: 'Create account',
    subtitle: 'Create an account to save your work and come back to it later.',
    submit: 'Create account',
    submitting: 'Creating account...',
    fallbackError: 'Could not create your account right now.',
    passwordMismatch: 'Password confirmation does not match.',
    switchPrompt: 'Already have an account?',
    switchAction: 'Sign in',
  },
  fields: {
    name: 'Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    namePlaceholder: 'Ada Lovelace',
    emailPlaceholder: 'you@example.com',
    passwordPlaceholder: '********',
  },
  modal: {
    loginTitle: 'Login',
    registerTitle: 'Create account',
  },
  workspace: {
    loadingSession: 'Loading your session...',
    checkingSession: 'Checking your session...',
    sessionVerificationFailed: 'Could not verify your session right now.',
    signInForElements: 'Sign in to view the element data.',
    loadingPeriodicTable: 'Loading the periodic table...',
    signInForEditor: 'Sign in to use the molecular editor.',
    signInForGallery: 'Sign in to open your molecule gallery.',
    loadingElementLibrary: 'Loading the element library...',
  },
} as const;
