export const authTextPt = {
  common: {
    close: 'Fechar',
    tryAgain: 'Tentar novamente',
    openLogin: 'Abrir login',
  },
  login: {
    eyebrow: 'Que bom te ver de novo',
    title: 'Entrar',
    subtitle: 'Entre para salvar seu trabalho e manter seus dados de química em sincronia.',
    submit: 'Entrar',
    submitting: 'Entrando...',
    fallbackError: 'Não foi possível entrar agora.',
    switchPrompt: 'Precisa de uma conta?',
    switchAction: 'Cadastre-se aqui',
  },
  register: {
    eyebrow: 'Vamos começar',
    title: 'Criar conta',
    subtitle: 'Crie uma conta para salvar seu trabalho e voltar a ele depois.',
    submit: 'Criar conta',
    submitting: 'Criando conta...',
    fallbackError: 'Não foi possível criar sua conta agora.',
    passwordMismatch: 'A confirmação da senha não confere.',
    switchPrompt: 'Já tem uma conta?',
    switchAction: 'Entrar',
  },
  fields: {
    name: 'Nome',
    email: 'E-mail',
    password: 'Senha',
    confirmPassword: 'Confirmar senha',
    namePlaceholder: 'Ada Lovelace',
    emailPlaceholder: 'voce@exemplo.com',
    passwordPlaceholder: '********',
  },
  modal: {
    loginTitle: 'Entrar',
    registerTitle: 'Criar conta',
  },
  workspace: {
    loadingSession: 'Carregando sua sessão...',
    checkingSession: 'Verificando sua sessão...',
    sessionVerificationFailed: 'Não foi possível verificar sua sessão agora.',
    signInForElements: 'Entre para ver os dados dos elementos.',
    loadingPeriodicTable: 'Carregando a tabela periódica...',
    signInForEditor: 'Entre para usar o editor molecular.',
    signInForGallery: 'Entre para abrir sua galeria de moléculas.',
    loadingElementLibrary: 'Carregando a biblioteca de elementos...',
  },
} as const;
