export const authTextEn = {
  common: {
    close: 'Close',
    tryAgain: 'Try again',
    openLogin: 'Sign in',
  },
  login: {
    eyebrow: 'Welcome back',
    title: 'Login',
    subtitle: 'Sign in to save your work and pick up where you left off.',
    submit: 'Sign in',
    submitting: 'Signing in...',
    fallbackError: 'Could not sign in right now.',
    switchPrompt: 'Need an account?',
    switchAction: 'Register here',
  },
  register: {
    eyebrow: 'Get started',
    title: 'Create account',
    subtitle: 'Create an account to save your work and come back to it later.',
    submit: 'Create account',
    submitting: 'Creating account...',
    fallbackError: 'Could not create your account right now.',
    passwordMismatch: 'Password confirmation does not match.',
    switchPrompt: 'Already have an account?',
    switchAction: 'Sign in',
  },
  fields: {
    name: 'Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    namePlaceholder: 'Ada Lovelace',
    emailPlaceholder: 'you@example.com',
    passwordPlaceholder: '********',
  },
  modal: {
    loginTitle: 'Login',
    registerTitle: 'Create account',
  },
  workspace: {
    loadingSession: 'Loading...',
    checkingSession: 'Checking your access...',
    sessionVerificationFailed: 'We could not confirm your access right now.',
    sessionVerificationFailedNetwork: 'We could not confirm your access. Check your connection and try again.',
    sessionExpired: 'Your session ended. Sign in again to continue.',
    signInForElements: 'Sign in to explore the elements.',
    loadingPeriodicTable: 'Loading the periodic table...',
    loadingElementsFailed: 'We could not load the elements right now.',
    loadingElementsFailedNetwork: 'We could not load the elements. Check your connection and try again.',
    signInForEditor: 'Sign in to use the molecular editor.',
    signInForGallery: 'Sign in to open your molecule gallery.',
    loadingElementLibrary: 'Loading elements...',
    loadingSavedMoleculesFailed: 'We could not load your saved molecules right now.',
    loadingSavedMoleculesFailedNetwork:
      'We could not load your saved molecules. Check your connection and try again.',
  },
} as const;
