export const authTextPt = {
  common: {
    close: 'Fechar',
    tryAgain: 'Tentar novamente',
    openLogin: 'Entrar',
  },
  login: {
    eyebrow: 'Que bom te ver de novo',
    title: 'Entrar',
    subtitle: 'Entre para salvar seu trabalho e continuar de onde parou.',
    submit: 'Entrar',
    submitting: 'Entrando...',
    networkError: 'Não conseguimos acessar o serviço de login. Tente de novo.',
    invalidCredentials: 'Esse e-mail ou senha não confere.',
    rateLimited: 'Houve muitas tentativas. Aguarde um pouco e tente de novo.',
    fallbackError: 'Não foi possível entrar agora.',
    switchPrompt: 'Precisa de uma conta?',
    switchAction: 'Cadastre-se aqui',
  },
  register: {
    eyebrow: 'Vamos começar',
    title: 'Criar conta',
    subtitle: 'Crie uma conta para salvar seu trabalho e voltar a ele depois.',
    submit: 'Criar conta',
    submitting: 'Criando conta...',
    networkError: 'Não conseguimos acessar o serviço de cadastro. Tente de novo.',
    emailInUse: 'Esse e-mail já está em uso.',
    weakPassword: 'Escolha uma senha mais forte para continuar.',
    invalidEmail: 'Confira seu e-mail e tente de novo.',
    invalidName: 'Confira seu nome e tente de novo.',
    rateLimited: 'Houve muitas tentativas. Aguarde um pouco e tente de novo.',
    fallbackError: 'Não foi possível criar sua conta agora.',
    passwordMismatch: 'A confirmação da senha não confere.',
    switchPrompt: 'Já tem uma conta?',
    switchAction: 'Entrar',
  },
  fields: {
    name: 'Nome',
    email: 'E-mail',
    password: 'Senha',
    confirmPassword: 'Confirmar senha',
    namePlaceholder: 'Ada Lovelace',
    emailPlaceholder: 'voce@exemplo.com',
    passwordPlaceholder: '********',
  },
  modal: {
    loginTitle: 'Entrar',
    registerTitle: 'Criar conta',
  },
  workspace: {
    loadingSession: 'Carregando...',
    checkingSession: 'Confirmando seu acesso...',
    sessionVerificationFailed: 'Não conseguimos confirmar seu acesso agora.',
    sessionVerificationFailedNetwork: 'Não conseguimos confirmar seu acesso. Verifique sua conexão e tente de novo.',
    sessionExpired: 'Sua sessão terminou. Entre de novo para continuar.',
    signInForElements: 'Entre para explorar os elementos.',
    loadingPeriodicTable: 'Carregando a tabela periódica...',
    loadingElementsFailed: 'Não conseguimos carregar os elementos agora.',
    loadingElementsFailedNetwork: 'Não conseguimos carregar os elementos. Verifique sua conexão e tente de novo.',
    signInForEditor: 'Entre para usar o editor molecular.',
    signInForGallery: 'Entre para abrir sua galeria de moléculas.',
    loadingElementLibrary: 'Carregando elementos...',
    loadingSavedMoleculesFailed: 'Não conseguimos carregar suas moléculas salvas agora.',
    loadingSavedMoleculesFailedNetwork:
      'Não conseguimos carregar suas moléculas salvas. Verifique sua conexão e tente de novo.',
  },
} as const;
