'use client';

import { memo, useMemo } from 'react';

import MoleculeGallerySection from '@/components/organisms/molecular-editor/MoleculeGallerySection';
import MoleculeEditorOverlays from '@/components/organisms/molecular-editor/MoleculeEditorOverlays';
import MoleculeEditorSection from '@/components/organisms/molecular-editor/MoleculeEditorSection';
import {
  BOND_ORDER_OPTIONS,
  DEFAULT_EDITOR_NOTICE,
  VIEW_OPTIONS,
} from '@/components/organisms/molecular-editor/moleculeEditorConfig';
import useMoleculeEditorLayout from '@/components/organisms/molecular-editor/useMoleculeEditorLayout';
import useMoleculeEditorOverlayProps from '@/components/organisms/molecular-editor/useMoleculeEditorOverlayProps';
import {
  resolveInteractiveViewBox,
} from '@/components/organisms/molecular-editor/moleculeCanvasViewport';
import useMoleculePaletteController from '@/components/organisms/molecular-editor/useMoleculePaletteController';
import useMoleculeEditorSession from '@/components/organisms/molecular-editor/useMoleculeEditorSession';
import useMolecularEditorRuntime from '@/components/organisms/molecular-editor/useMolecularEditorRuntime';
import useMoleculeEditorState from '@/components/organisms/molecular-editor/useMoleculeEditorState';
import useMoleculeEditorSectionProps from '@/components/organisms/molecular-editor/useMoleculeEditorSectionProps';
import useMoleculeGallerySectionProps from '@/components/organisms/molecular-editor/useMoleculeGallerySectionProps';
import useSavedMoleculeEditorWorkflow from '@/components/organisms/molecular-editor/useSavedMoleculeEditorWorkflow';
import type {
  SaveMoleculeInput,
  SavedMolecule,
} from '@/shared/types/molecule';
import type { ChemicalElement } from '@/shared/types/element';

type MolecularEditorProps = {
  pageMode: 'editor' | 'gallery';
  elements: ChemicalElement[];
  savedMolecules: SavedMolecule[];
  savedMoleculesError: string | null;
  isSavedMoleculesLoading: boolean;
  isSavedMoleculesMutating: boolean;
  onReloadSavedMolecules: () => void;
  onCreateSavedMolecule: (input: SaveMoleculeInput) => Promise<SavedMolecule>;
  onUpdateSavedMolecule: (moleculeId: string, input: SaveMoleculeInput) => Promise<SavedMolecule>;
  onDeleteSavedMolecule: (moleculeId: string) => Promise<void>;
};

function MolecularEditor({
  pageMode,
  elements,
  savedMolecules,
  savedMoleculesError,
  isSavedMoleculesLoading,
  isSavedMoleculesMutating,
  onReloadSavedMolecules,
  onCreateSavedMolecule,
  onUpdateSavedMolecule,
  onDeleteSavedMolecule,
}: MolecularEditorProps) {
  const {
    activeSavedMoleculeId,
    activeView,
    bondOrder,
    canvasViewport,
    clearPendingCanvasPlacementRef,
    clearTransientEditorStateRef,
    editorNotice,
    focusedComponentIndex,
    isFloatingSaveShortcutExpanded,
    isFormulaPanelOpen,
    isImportModalOpen,
    isToolRailCollapsed,
    molecule,
    moleculeEducationalDescription,
    moleculeName,
    nomenclatureFallback,
    onCloseImportModal,
    onOpenImportModal,
    onSetActiveView,
    onSetBondOrder,
    selectedAtomId,
    setActiveSavedMoleculeId,
    setActiveView,
    setBondOrder,
    setCanvasViewport,
    setEditorNotice,
    setFocusedComponentIndex,
    setIsFloatingSaveShortcutExpanded,
    setIsFormulaPanelOpen,
    setIsImportModalOpen,
    setIsToolRailCollapsed,
    setMolecule,
    setMoleculeEducationalDescription,
    setMoleculeName,
    setNomenclatureFallback,
    setSelectedAtomId,
    svgRef,
  } = useMoleculeEditorState();

  const {
    activeElement,
    filteredElements,
    goToNextPaletteElement,
    goToPreviousPaletteElement,
    hasActivePaletteFilter,
    isPaletteMoving,
    isPalettePointerActive,
    isPaletteSearchOpen,
    onClearPaletteSearch,
    onClosePaletteSearch,
    onPaletteItemRef,
    onPalettePointerCancel,
    onPalettePointerDown,
    onPalettePointerMove,
    onPalettePointerUp,
    onPaletteScroll,
    onPaletteSearchChange,
    onTogglePaletteSearch,
    paletteEdgePadding,
    paletteQuery,
    paletteSearchRailRef,
    paletteViewportRef,
    resolvedCenterPaletteIndex,
    resolvedExpandedPaletteIndex,
    searchInputRef,
  } = useMoleculePaletteController({ elements });

  const {
    activeElementMaxBondSlots,
    applyEditorSnapshot,
    buildHistorySnapshot,
    buildSaveMoleculeInput,
    canRedo,
    canUndo,
    clearHistory,
    compositionRows,
    focusedSummary,
    formula,
    formulaDisplayValue,
    formulaStatsRows,
    galleryFeedback,
    moleculeComponents,
    normalizedSavedMolecules,
    onRedo,
    onUndo,
    pushHistorySnapshot,
    resolvedFocusedComponentIndex,
    showGalleryFeedback,
    summary,
    systematicNameDisplayValue,
  } = useMoleculeEditorSession({
    activeElement,
    activeView,
    bondOrder,
    canvasViewport,
    clearTransientEditorStateRef,
    focusedComponentIndex,
    molecule,
    moleculeEducationalDescription,
    moleculeName,
    nomenclatureFallback,
    savedMolecules,
    selectedAtomId,
    setActiveView,
    setBondOrder,
    setCanvasViewport,
    setEditorNotice,
    setFocusedComponentIndex,
    setMolecule,
    setNomenclatureFallback,
    setSelectedAtomId,
  });

  const {
    currentSaveLabel,
    hasCheckedPendingSavedMolecule,
    hasCurrentSavedSelection,
    hasPendingSavedMolecule,
    isSaveModalOpen,
    onCloseSaveModal,
    onDeleteCurrentSavedMolecule,
    onDeleteCurrentSavedMoleculeFromGallery,
    onDetachSavedMolecule,
    onLoadSavedMolecule,
    onOpenCurrentSavedMoleculeInEditor,
    onOpenGalleryEditModal,
    onOpenSaveModal,
    onSaveAsNewMolecule,
    onUpdateCurrentSavedMolecule,
    resolvedActiveSavedMoleculeId,
  } = useSavedMoleculeEditorWorkflow({
    activeSavedMoleculeId,
    applyEditorSnapshot,
    buildSaveMoleculeInput,
    closeImportModal: onCloseImportModal,
    collapseFloatingSaveShortcut: () => setIsFloatingSaveShortcutExpanded(false),
    clearHistory,
    formula,
    isSavedMoleculesLoading,
    moleculeName,
    normalizedSavedMolecules,
    onCreateSavedMolecule,
    onDeleteSavedMolecule,
    onUpdateSavedMolecule,
    pageMode,
    setActiveSavedMoleculeId,
    setMoleculeEducationalDescription,
    setMoleculeName,
    setNomenclatureFallback,
    showGalleryFeedback,
    summaryAtomCount: summary.atomCount,
  });

  const resolvedEditorNotice =
    editorNotice ??
    (hasCheckedPendingSavedMolecule &&
    !hasPendingSavedMolecule &&
    summary.atomCount === 0 &&
    selectedAtomId === null
      ? DEFAULT_EDITOR_NOTICE
      : null);
  const {
    bottomNoticeRef,
    canvasFrameAspectRatio,
    canvasFrameClassName,
    canvasFrameRef,
    canvasFrameSize,
    canvasPanelClassName,
    canvasPanelStyle,
    collapsedToolRailSectionClassName,
    compactBottomNoticeClassName,
    compactBottomOverlayClassName,
    compactDisplayedEditorNotice,
    editorSectionStyle,
    effectiveToolRailCollapsed,
    expandedToolRailSectionClassName,
    floatingSaveShortcutInnerStyle,
    floatingSaveShortcutPanelStyle,
    floatingSaveShortcutTriggerStyle,
    formulaPanelStyle,
    importButtonClassName,
    isLandscapeCompactCanvas,
    isSimplifiedView,
    paletteRowClassName,
    paletteSearchButtonClassName,
    paletteSearchInnerStyle,
    paletteSearchPanelStyle,
    paletteSearchRailStyle,
    paletteSearchShellClassName,
    paletteSearchTriggerStyle,
    paletteViewportWrapperClassName,
    responsiveLayoutWidth,
    showExpandedToolRailContent,
    simplifiedViewStyle,
    toolRailBodyClassName,
    toolRailCollapsedWidthClassName,
    toolRailExpandedWidthClassName,
    toolRailStyle,
    topControlsBlockClassName,
    topControlsLeadingGroupClassName,
    topControlsRef,
    topControlsRowClassName,
    topOverlayClassName,
    topOverlayRef,
    viewModeButtonClassName,
    viewModeTabsClassName,
    zoomControlsClassName,
    zoomControlsVisibilityClassName,
  } = useMoleculeEditorLayout({
    activeView,
    componentCount: moleculeComponents.length,
    isFloatingSaveShortcutExpanded,
    isFormulaPanelOpen,
    isPaletteSearchOpen,
    isToolRailCollapsed,
    pageMode,
    paletteSearchRailRef,
    resolvedEditorNotice,
  });
  const interactiveViewBox = useMemo(
    () => resolveInteractiveViewBox(molecule, canvasViewport, canvasFrameAspectRatio),
    [canvasFrameAspectRatio, canvasViewport, molecule],
  );
  const zoomPercent = Math.round(canvasViewport.scale * 100);

  const {
    onAddSelectedElement,
    onAtomPointerDown,
    onCanvasPointerCancel,
    onCanvasPointerDown,
    onCanvasPointerMove,
    onCanvasPointerUp,
    onCanvasWheel,
    onClearSelection,
    onFocusComponent,
    onImportExternalMolecule,
    onRemoveSelectedAtom,
    onResetCanvasView,
    onResetMolecule,
    onZoomIn,
    onZoomOut,
  } = useMolecularEditorRuntime({
    activeElement,
    activeView,
    applyEditorSnapshot,
    bondOrder,
    buildHistorySnapshot,
    canvasFrameAspectRatio,
    canvasFrameSize,
    canvasViewport,
    clearPendingCanvasPlacementRef,
    clearTransientEditorStateRef,
    isImportModalOpen,
    isSaveModalOpen,
    molecule,
    moleculeComponents,
    onRedo,
    onUndo,
    pageMode,
    pushHistorySnapshot,
    selectedAtomId,
    setActiveSavedMoleculeId,
    setActiveView,
    setBondOrder,
    setCanvasViewport,
    setEditorNotice,
    setFocusedComponentIndex,
    setIsImportModalOpen,
    setMolecule,
    setMoleculeEducationalDescription,
    setMoleculeName,
    setNomenclatureFallback,
    setSelectedAtomId,
    showGalleryFeedback,
    svgRef,
  });

  const isEditorPage = pageMode === 'editor';
  const isGalleryPage = pageMode === 'gallery';
  const shouldShowToolRail = isEditorPage && activeView === 'editor';
  const shouldShowFloatingSaveShortcut = isEditorPage && activeView !== 'editor';
  const shouldShowComponentFocusRail = moleculeComponents.length > 1;
  const editorSectionProps = useMoleculeEditorSectionProps({
    activeElementMaxBondSlots,
    activeElementSymbol: activeElement?.symbol ?? null,
    activeView,
    bondOrder,
    bondOrderOptions: BOND_ORDER_OPTIONS,
    bottomNoticeRef,
    canRedo,
    canUndo,
    canvasFrameClassName,
    canvasFrameRef,
    canvasPanelClassName,
    canvasPanelStyle,
    collapsedToolRailSectionClassName,
    compactBottomNoticeClassName,
    compactBottomOverlayClassName,
    compactDisplayedEditorNotice,
    compositionRows,
    effectiveToolRailCollapsed,
    expandedToolRailSectionClassName,
    filteredElements,
    floatingSaveShortcutInnerStyle,
    floatingSaveShortcutPanelStyle,
    floatingSaveShortcutTriggerStyle,
    focusedComponentIndex: resolvedFocusedComponentIndex,
    formulaDisplayValue,
    formulaPanelStyle,
    formulaStatsRows,
    goToNextPaletteElement,
    goToPreviousPaletteElement,
    hasActivePaletteFilter,
    importButtonClassName,
    interactiveViewBox,
    isFloatingSaveShortcutExpanded,
    isFormulaPanelOpen,
    isLandscapeCompactCanvas,
    isPaletteMoving,
    isPalettePointerActive,
    isPaletteSearchOpen,
    isSaveModalOpen,
    isSimplifiedView,
    molecule,
    moleculeComponents,
    onAddSelectedElement,
    onAtomPointerDown,
    onCanvasPointerCancel,
    onCanvasPointerDown,
    onCanvasPointerMove,
    onCanvasPointerUp,
    onCanvasWheel,
    onClearPaletteSearch,
    onClearSelection,
    onClosePaletteSearch,
    onFocusComponent,
    onFloatingSaveShortcutExpandedChange: setIsFloatingSaveShortcutExpanded,
    onItemRef: onPaletteItemRef,
    onOpenImportModal: () => onOpenImportModal(onCloseSaveModal),
    onOpenSaveModal,
    onPalettePointerCancel,
    onPalettePointerDown,
    onPalettePointerMove,
    onPalettePointerUp,
    onPaletteScroll,
    onPaletteSearchChange,
    onRedo,
    onRemoveSelectedAtom,
    onResetCanvasView,
    onResetMolecule,
    onSetActiveView,
    onSetBondOrder,
    onToggleCollapsed: () => setIsToolRailCollapsed((current) => !current),
    onToggleFormulaPanel: () => setIsFormulaPanelOpen((current) => !current),
    onTogglePaletteSearch,
    onUndo,
    onZoomIn,
    onZoomOut,
    overlayRef: topOverlayRef,
    overlayClassName: topOverlayClassName,
    paletteEdgePadding,
    paletteQuery,
    paletteRowClassName,
    paletteSearchButtonClassName,
    paletteSearchInnerStyle,
    paletteSearchPanelStyle,
    paletteSearchRailRef,
    paletteSearchRailStyle,
    paletteSearchShellClassName,
    paletteSearchTriggerStyle,
    paletteViewportRef,
    paletteViewportWrapperClassName,
    resolvedCenterPaletteIndex,
    resolvedEditorNotice,
    resolvedExpandedPaletteIndex,
    responsiveLayoutWidth,
    searchInputRef,
    selectedAtomId,
    shouldShowComponentFocusRail,
    shouldShowFloatingSaveShortcut,
    shouldShowToolRail,
    showExpandedToolRailContent,
    simplifiedViewStyle,
    summaryAtomCount: summary.atomCount,
    svgRef,
    toolRailBodyClassName,
    toolRailCollapsedWidthClassName,
    toolRailExpandedWidthClassName,
    toolRailStyle,
    topControlsBlockClassName,
    topControlsLeadingGroupClassName,
    topControlsRef,
    topControlsRowClassName,
    viewModeButtonClassName,
    viewModeTabsClassName,
    viewOptions: VIEW_OPTIONS,
    zoomControlsClassName,
    zoomControlsVisibilityClassName,
    zoomPercent,
  });
  const gallerySectionProps = useMoleculeGallerySectionProps({
    savedMolecules: normalizedSavedMolecules,
    activeSavedMoleculeId: resolvedActiveSavedMoleculeId,
    galleryFeedback,
    savedMoleculesError,
    isSavedMoleculesLoading,
    isSavedMoleculesMutating,
    onOpenGalleryEditModal,
    onOpenCurrentSavedMoleculeInEditor,
    onDeleteCurrentSavedMoleculeFromGallery,
    onReloadSavedMolecules,
    onLoadSavedMolecule,
  });
  const overlayProps = useMoleculeEditorOverlayProps({
    componentCount: moleculeComponents.length,
    currentSaveLabel,
    elements,
    feedback: galleryFeedback,
    focusedAtomCount: focusedSummary.atomCount,
    focusedBondCount: focusedSummary.bondCount,
    focusedComponentIndex: resolvedFocusedComponentIndex,
    formula: formulaDisplayValue,
    hasLinkedSelection: hasCurrentSavedSelection,
    isImportModalOpen,
    isMutating: isSavedMoleculesMutating,
    isSaveModalOpen,
    moleculeEducationalDescription,
    moleculeTitle: moleculeName,
    nomenclature: systematicNameDisplayValue,
    onCloseImportModal,
    onCloseSaveModal,
    onDeleteSelected: onDeleteCurrentSavedMolecule,
    onDetachSelection: onDetachSavedMolecule,
    onEducationalDescriptionChange: setMoleculeEducationalDescription,
    onImport: onImportExternalMolecule,
    onMoleculeTitleChange: setMoleculeName,
    onSaveAsNew: onSaveAsNewMolecule,
    onUpdateSelected: onUpdateCurrentSavedMolecule,
    pageMode,
  });

  return (
    <section className="flex min-h-0 flex-col gap-3 overflow-visible pb-4" style={editorSectionStyle}>
      {isEditorPage ? <MoleculeEditorSection {...editorSectionProps} /> : null}

      {isGalleryPage ? <MoleculeGallerySection {...gallerySectionProps} /> : null}

      <MoleculeEditorOverlays {...overlayProps} />
    </section>
  );
}

export default memo(MolecularEditor);
