export const molecularEditorTextEn = {
  common: {
    close: 'Close',
    loading: 'Loading...',
    yes: 'Yes',
    no: 'No',
    notAvailable: 'N/A',
    unavailable: 'Unavailable',
    unsavedMolecule: 'Unsaved molecule',
  },
  workspace: {
    loadingEditor: 'Loading editor...',
  },
  viewOptions: {
    editor: 'Editor',
    structural: 'Structural',
    simplified: 'Simplified',
    stick: 'Stick',
  },
  bondOrders: {
    1: 'Single',
    2: 'Double',
    3: 'Triple',
  },
  topBar: {
    import: 'Import',
    importOther: 'Import Other',
    importAnotherMolecule: 'Import another molecule',
    importFromPubChem: 'Import another molecule from PubChem',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    resetZoom: 'Reset zoom',
    fit: 'Fit',
  },
  toolRail: {
    tools: 'Tools',
    expand: 'Expand tools',
    collapse: 'Collapse tools',
    saveAsNew: 'Save As New',
    saveDialog: 'Save molecule',
    undo: 'Undo',
    undoTitle: 'Undo change (Ctrl/Cmd+Z)',
    redo: 'Redo',
    redoTitle: 'Redo change (Ctrl/Cmd+Shift+Z)',
    addSelectedElement: 'Add selected element',
    removeSelectedAtom: 'Remove selected atom',
    clearSelection: 'Clear selection',
    resetEditor: 'Reset editor',
    bondOrder: 'Bond Order',
    supportsUpTo: 'supports up to',
    bondSlotSingular: 'bond slot',
    bondSlotPlural: 'bond slots',
  },
  palette: {
    searchPlaceholder: 'Search elements',
    clearSearch: 'Clear element search',
    openSearch: 'Open element search',
    closeSearch: 'Close element search',
    previousElement: 'Select previous element',
    nextElement: 'Select next element',
    selectElementPrefix: 'Select',
  },
  importModal: {
    title: 'Import Molecule',
    sourceLabel: 'Source',
    sourceName: 'PubChem',
    intro: 'Search PubChem and import a compound.',
    search: 'Search',
    searchPlaceholder: 'caffeine, aspirin, benzene...',
    relatedTerms: 'Related Terms',
    relatedTermsIdle: 'Start typing to see related terms.',
    relatedTermsEmpty: 'No related terms found yet.',
    importScope: 'Import Scope',
    importScopeDescription: 'Choose what to bring into the canvas.',
    mainComponent: 'Main component',
    mainComponentDescription: 'Import only the main component.',
    allComponents: 'All components',
    allComponentsDescription: 'Import every component together.',
    results: 'Search Results',
    resultsIdle: 'Search to see matching compounds.',
    resultsForPrefix: 'Showing compounds for',
    searching: 'Searching...',
    searchPrompt: 'Search by common name or IUPAC fragment.',
    noResults: 'No matches found yet.',
    importing: 'Importing...',
    import: 'Import',
    importIntoEditor: 'Import into Editor',
    formulaUnavailable: 'Formula unavailable',
    noIupac: 'No IUPAC name available for this record.',
  },
  saveModal: {
    editGalleryRecord: 'Edit Saved Molecule',
    saveMoleculeToGallery: 'Save Molecule',
    galleryRecord: 'Saved item',
    gallerySave: 'Save',
    galleryRecordDescription: 'Update the selected saved molecule.',
    gallerySaveDescription: 'Save this molecule or update the selected entry.',
    linkedRecord: 'Linked item',
    newDraft: 'New draft',
    title: 'Title',
    description: 'Description',
    markdownHint: 'Markdown supported: bold, lists, links, and code.',
    titlePlaceholder: 'Benzene',
    descriptionPlaceholder: 'Add a short description or note about this molecule.',
    updateSelected: 'Update Selected',
    saveAsNew: 'Save As New',
    delete: 'Delete',
    savedRecord: 'Saved item',
    currentCanvas: 'Current molecule',
    componentFocus: 'Component',
    nomenclature: 'Nomenclature',
    formula: 'Formula',
    atoms: 'Atoms',
    bonds: 'Bonds',
    components: 'Components',
    addAtomsBeforeSaving: 'Add atoms before saving.',
    updateHint: 'Save changes to this item.',
    saveHint: 'Save a new item or update the selected one.',
  },
  gallery: {
    eyebrow: 'Gallery',
    title: 'Saved Molecules',
    savedSuffix: 'saved',
    editDetails: 'Edit Details',
    openInEditor: 'Open in Editor',
    delete: 'Delete',
    refresh: 'Refresh',
    loading: 'Loading your saved molecules...',
    emptyTitle: 'No saved molecules yet.',
    emptyDescription: 'Save molecules in the editor to see them here.',
    syncStatus: 'Sync Status',
    savedStatus: 'Saved',
    retrySync: 'Retry sync',
    active: 'Active',
    nomenclature: 'Nomenclature',
    atoms: 'Atoms',
    bonds: 'Bonds',
    saved: 'Saved',
    description: 'Description',
    componentsSuffix: 'components',
    unknownSyncTime: 'Unknown sync time',
    previewPrefix: 'Preview of',
  },
  summary: {
    title: 'Summary',
    show: 'Show summary',
    hide: 'Hide summary',
    nomenclature: 'Nomenclature',
    nomenclatureShort: 'Nomen.',
    formula: 'Formula',
    atoms: 'Atoms',
    bonds: 'Bonds',
    slots: 'Slots',
    component: 'Component',
    componentShort: 'Comp.',
  },
  componentRail: {
    componentsSuffix: 'components',
    focusComponent: 'Focus component',
    moleculeShort: 'Mol',
  },
  simplifiedView: {
    title: 'Simplified',
    currentMoleculeDescription: 'Quick formula view for the current molecule.',
    componentDescriptionPrefix: 'Quick formula view for component',
    empty: 'Add atoms to see a simplified formula.',
  },
  canvas: {
    ariaLabel: 'Molecule editor canvas',
  },
  feedback: {
    syncIssue: 'Sync issue',
    workSaved: 'Work saved',
    galleryReady: 'Gallery ready',
    saving: 'Saving',
    gallery: 'Gallery',
  },
  notices: {
    defaultEditorNotice: 'Select an element, then double-click or double-tap the canvas to place it.',
    compactDefaultEditorNotice: 'Select an element, then double-tap to place it.',
    selectionCleared: 'Selection cleared.',
    atomSelected: 'Atom selected. Tap another atom to create a bond or use the tools to attach the active element.',
    canvasViewReset: 'Canvas view reset.',
    selectAtomBeforeRemoving: 'Select an atom before removing it.',
    selectedAtomRemoved: 'Selected atom removed.',
    componentFocusedPrefix: 'Component',
    componentFocusedSuffix: 'focused.',
    bondUpdatedPrefix: 'Bond updated to order',
    doubleTapSelectionClear: 'Double-tap again to attach the active element, or wait to clear the selection.',
    doubleClickSelectionClear: 'Double-click again to attach the active element, or wait to clear the selection.',
    doubleTapPlacement: 'Double-tap the canvas to place the active element.',
    doubleClickPlacement: 'Double-click the canvas to place the active element.',
    addedToCanvasSuffix: 'added to the canvas.',
    placedOnCanvasSuffix: 'placed on the canvas.',
    attachedToSelectedAtomSuffix: 'attached to the selected atom.',
    linkedWithBondPrefix: 'linked with a',
    linkedWithBondSuffix: 'bond.',
    editorAlreadyReset: 'Editor is already clear.',
    editorReset: 'Editor cleared.',
    noElementMatchesSearch: 'No element matches the current search.',
    chooseElementBeforePlacing: 'Choose an element before placing atoms.',
    addAtomsBeforeSaving: 'Add atoms before saving.',
    saveRequestSent: 'Saving...',
    selectSavedBeforeUpdating: 'Select a saved molecule before updating it.',
    addAtomsBeforeUpdating: 'Add atoms before updating this molecule.',
    selectSavedBeforeDeleting: 'Select a saved molecule before deleting it.',
    deleteRequestSent: 'Deleting...',
    savedWorkDeleted: 'Saved molecule deleted.',
    currentCanvasDetached: 'The current canvas is no longer linked. Saving now will create a new entry.',
    selectSavedBeforeEditing: 'Select a saved molecule before editing its details.',
    selectSavedBeforeOpening: 'Select a saved molecule before opening it in the editor.',
    loadedSuffix: 'loaded.',
    issueSameAtomBond: 'Choose two different atoms to create a bond.',
    issueMissingBondAtom: 'One of the selected atoms is no longer available.',
    issueMissingSourceAtom: 'Select an atom before attaching a new one.',
    issueNoAttachmentPoint: 'We could not find a good place for the new atom.',
    issueBondLimitReachedPrefix: '',
    issueBondLimitReachedMiddle: 'supports up to',
    issueBondLimitReachedSingle: 'bond slot.',
    issueBondLimitReachedPlural: 'bond slots.',
    issueTargetBondOrderUnsupportedPrefix: '',
    issueTargetBondOrderUnsupportedMiddle: 'cannot start with bond order',
    issueTargetBondOrderUnsupportedSuffix: 'with the current valence rule.',
  },
} as const;
