export const molecularEditorTextPt = {
  common: {
    close: 'Fechar',
    loading: 'Carregando...',
    yes: 'Sim',
    no: 'Não',
    notAvailable: 'N/D',
    unavailable: 'Indisponível',
    unsavedMolecule: 'Molécula não salva',
  },
  workspace: {
    loadingEditor: 'Carregando editor...',
  },
  viewOptions: {
    editor: 'Editor',
    structural: 'Estrutural',
    simplified: 'Simplificado',
    stick: 'Palitos',
  },
  bondOrders: {
    1: 'Simples',
    2: 'Dupla',
    3: 'Tripla',
  },
  topBar: {
    import: 'Importar',
    importOther: 'Importar outra',
    importAnotherMolecule: 'Importar outra molécula',
    importFromPubChem: 'Importar outra molécula do PubChem',
    zoomIn: 'Aumentar zoom',
    zoomOut: 'Reduzir zoom',
    resetZoom: 'Redefinir zoom',
    fit: 'Ajuste',
  },
  toolRail: {
    tools: 'Ferramentas',
    expand: 'Expandir ferramentas',
    collapse: 'Recolher ferramentas',
    saveAsNew: 'Salvar como nova',
    saveDialog: 'Salvar molécula',
    undo: 'Desfazer',
    undoTitle: 'Desfazer alteração (Ctrl/Cmd+Z)',
    redo: 'Refazer',
    redoTitle: 'Refazer alteração (Ctrl/Cmd+Shift+Z)',
    addSelectedElement: 'Adicionar elemento selecionado',
    removeSelectedAtom: 'Remover átomo selecionado',
    clearSelection: 'Limpar seleção',
    resetEditor: 'Limpar editor',
    bondOrder: 'Ordem da ligação',
    supportsUpTo: 'suporta até',
    bondSlotSingular: 'slot de ligação',
    bondSlotPlural: 'slots de ligação',
  },
  palette: {
    searchPlaceholder: 'Buscar elementos',
    clearSearch: 'Limpar busca de elementos',
    openSearch: 'Abrir busca de elementos',
    closeSearch: 'Fechar busca de elementos',
    previousElement: 'Selecionar elemento anterior',
    nextElement: 'Selecionar próximo elemento',
    selectElementPrefix: 'Selecionar',
  },
  importModal: {
    title: 'Importar molécula',
    sourceLabel: 'Fonte',
    sourceName: 'PubChem',
    intro: 'Pesquise no PubChem e importe um composto.',
    search: 'Pesquisar',
    searchPlaceholder: 'cafeína, aspirina, benzeno...',
    relatedTerms: 'Termos relacionados',
    relatedTermsIdle: 'Comece a digitar para ver termos relacionados.',
    relatedTermsEmpty: 'Ainda não encontramos termos relacionados.',
    importScope: 'Escopo do import',
    importScopeDescription: 'Escolha o que entra no canvas.',
    mainComponent: 'Componente principal',
    mainComponentDescription: 'Importa só o componente principal.',
    allComponents: 'Todos os componentes',
    allComponentsDescription: 'Importa todos os componentes juntos.',
    results: 'Resultados',
    resultsIdle: 'Pesquise para ver compostos correspondentes.',
    resultsForPrefix: 'Mostrando compostos para',
    searching: 'Pesquisando...',
    searchPrompt: 'Pesquise por nome comum ou trecho do IUPAC.',
    noResults: 'Nenhum resultado encontrado ainda.',
    importing: 'Importando...',
    import: 'Importar',
    importIntoEditor: 'Importar para o editor',
    formulaUnavailable: 'Fórmula indisponível',
    noIupac: 'Nenhum nome IUPAC disponível para este registro.',
  },
  saveModal: {
    editGalleryRecord: 'Editar molécula salva',
    saveMoleculeToGallery: 'Salvar molécula',
    galleryRecord: 'Item salvo',
    gallerySave: 'Salvar',
    galleryRecordDescription: 'Atualize a molécula salva selecionada.',
    gallerySaveDescription: 'Salve esta molécula ou atualize a entrada selecionada.',
    linkedRecord: 'Item vinculado',
    newDraft: 'Novo rascunho',
    title: 'Título',
    description: 'Descrição',
    markdownHint: 'Markdown aceito: negrito, listas, links e código.',
    titlePlaceholder: 'Benzeno',
    descriptionPlaceholder: 'Adicione uma descrição curta ou uma nota sobre esta molécula.',
    updateSelected: 'Atualizar selecionada',
    saveAsNew: 'Salvar como nova',
    delete: 'Excluir',
    savedRecord: 'Item salvo',
    currentCanvas: 'Molécula atual',
    componentFocus: 'Componente',
    nomenclature: 'Nomenclatura',
    formula: 'Fórmula',
    atoms: 'Átomos',
    bonds: 'Ligações',
    components: 'Componentes',
    addAtomsBeforeSaving: 'Adicione átomos antes de salvar.',
    updateHint: 'Salve as alterações neste item.',
    saveHint: 'Salve um novo item ou atualize o item selecionado.',
  },
  gallery: {
    eyebrow: 'Galeria',
    title: 'Moléculas salvas',
    savedSuffix: 'salvas',
    editDetails: 'Editar detalhes',
    openInEditor: 'Abrir no editor',
    delete: 'Excluir',
    refresh: 'Atualizar',
    loading: 'Carregando suas moléculas salvas...',
    emptyTitle: 'Ainda não há moléculas salvas.',
    emptyDescription: 'Salve moléculas no editor para vê-las aqui.',
    syncStatus: 'Status da sincronização',
    savedStatus: 'Salvo',
    retrySync: 'Tentar de novo',
    active: 'Ativa',
    nomenclature: 'Nomenclatura',
    atoms: 'Átomos',
    bonds: 'Ligações',
    saved: 'Salva',
    description: 'Descrição',
    componentsSuffix: 'componentes',
    unknownSyncTime: 'Horário de sincronização desconhecido',
    previewPrefix: 'Prévia de',
  },
  summary: {
    title: 'Resumo',
    show: 'Mostrar resumo',
    hide: 'Ocultar resumo',
    nomenclature: 'Nomenclatura',
    nomenclatureShort: 'Nomen.',
    formula: 'Fórmula',
    atoms: 'Átomos',
    bonds: 'Ligações',
    slots: 'Slots',
    component: 'Componente',
    componentShort: 'Comp.',
  },
  componentRail: {
    componentsSuffix: 'componentes',
    focusComponent: 'Focar componente',
    moleculeShort: 'Mol',
  },
  simplifiedView: {
    title: 'Simplificado',
    currentMoleculeDescription: 'Visão rápida da fórmula da molécula atual.',
    componentDescriptionPrefix: 'Visão rápida da fórmula do componente',
    empty: 'Adicione átomos para ver a fórmula simplificada.',
  },
  canvas: {
    ariaLabel: 'Canvas do editor molecular',
  },
  feedback: {
    syncIssue: 'Problema de sincronização',
    workSaved: 'Salvo',
    galleryReady: 'Galeria pronta',
    saving: 'Salvando',
    gallery: 'Galeria',
  },
  notices: {
    defaultEditorNotice: 'Selecione um elemento e depois dê um clique duplo ou toque duplo no canvas para posicioná-lo.',
    compactDefaultEditorNotice: 'Selecione um elemento e toque duas vezes para posicioná-lo.',
    addedToCanvasSuffix: 'adicionado ao canvas.',
    placedOnCanvasSuffix: 'posicionado no canvas.',
    attachedToSelectedAtomSuffix: 'ligado ao átomo selecionado.',
    linkedWithBondPrefix: 'ligado com ligação',
    linkedWithBondSuffix: '.',
    editorAlreadyReset: 'O editor já está limpo.',
    editorReset: 'Editor limpo.',
    noElementMatchesSearch: 'Nenhum elemento corresponde à busca atual.',
    chooseElementBeforePlacing: 'Escolha um elemento antes de posicionar átomos.',
    addAtomsBeforeSaving: 'Adicione átomos antes de salvar.',
    saveRequestSent: 'Salvando...',
    selectSavedBeforeUpdating: 'Selecione uma molécula salva antes de atualizá-la.',
    addAtomsBeforeUpdating: 'Adicione átomos antes de atualizar esta molécula.',
    selectSavedBeforeDeleting: 'Selecione uma molécula salva antes de excluí-la.',
    deleteRequestSent: 'Excluindo...',
    savedWorkDeleted: 'Molécula salva excluída.',
    currentCanvasDetached: 'O canvas atual não está mais vinculado. Ao salvar agora, uma nova entrada será criada.',
    selectSavedBeforeEditing: 'Selecione uma molécula salva antes de editar seus detalhes.',
    selectSavedBeforeOpening: 'Selecione uma molécula salva antes de abri-la no editor.',
    loadedSuffix: 'carregada.',
  },
} as const;
