'use client';

import { useMemo } from 'react';

import type {
  CanvasPanelProps,
  PaletteRailProps,
  UseMoleculeEditorCanvasPanelPropsOptions,
} from '@/components/organisms/molecular-editor/moleculeEditorSectionProps.types';

export default function useMoleculeEditorCanvasPanelProps({
  activeView,
  bottomNoticeRef,
  canvasFrameClassName,
  canvasFrameRef,
  canvasPanelClassName,
  canvasPanelStyle,
  compactBottomNoticeClassName,
  compactBottomOverlayClassName,
  compactDisplayedEditorNotice,
  compositionRows,
  filteredElements,
  focusedComponentIndex,
  formulaDisplayValue,
  formulaPanelStyle,
  formulaStatsRows,
  goToNextPaletteElement,
  goToPreviousPaletteElement,
  hasActivePaletteFilter,
  interactiveViewBox,
  isFormulaPanelOpen,
  isLandscapeCompactCanvas,
  isPaletteMoving,
  isPalettePointerActive,
  isPaletteSearchOpen,
  isSimplifiedView,
  molecule,
  moleculeComponents,
  onAtomPointerDown,
  onCanvasPointerCancel,
  onCanvasPointerDown,
  onCanvasPointerMove,
  onCanvasPointerUp,
  onCanvasWheel,
  onClearPaletteSearch,
  onClosePaletteSearch,
  onItemRef,
  onPalettePointerCancel,
  onPalettePointerDown,
  onPalettePointerMove,
  onPalettePointerUp,
  onPaletteScroll,
  onPaletteSearchChange,
  onToggleFormulaPanel,
  onTogglePaletteSearch,
  overlayClassName,
  overlayRef,
  paletteEdgePadding,
  paletteQuery,
  paletteRowClassName,
  paletteSearchButtonClassName,
  paletteSearchInnerStyle,
  paletteSearchPanelStyle,
  paletteSearchRailRef,
  paletteSearchRailStyle,
  paletteSearchShellClassName,
  paletteSearchTriggerStyle,
  paletteViewportRef,
  paletteViewportWrapperClassName,
  resolvedCenterPaletteIndex,
  resolvedEditorNotice,
  resolvedExpandedPaletteIndex,
  searchInputRef,
  simplifiedViewStyle,
  svgRef,
  toolRailProps,
}: UseMoleculeEditorCanvasPanelPropsOptions): CanvasPanelProps {
  const formulaPanelProps = useMemo(
    () => ({
      isCompact: isLandscapeCompactCanvas,
      isOpen: isFormulaPanelOpen,
      rows: formulaStatsRows,
      style: formulaPanelStyle,
      onToggle: onToggleFormulaPanel,
    }),
    [isFormulaPanelOpen, isLandscapeCompactCanvas, formulaPanelStyle, formulaStatsRows, onToggleFormulaPanel],
  );

  const paletteRailProps = useMemo<PaletteRailProps>(
    () => ({
      overlayRef,
      overlayClassName,
      viewportRef: paletteViewportRef,
      elements: filteredElements,
      paletteEdgePadding,
      isCompact: isLandscapeCompactCanvas,
      isPaletteMoving,
      isPalettePointerActive,
      resolvedExpandedPaletteIndex,
      resolvedCenterPaletteIndex,
      wrapperClassName: paletteViewportWrapperClassName,
      rowClassName: paletteRowClassName,
      onPaletteScroll,
      onPalettePointerDown,
      onPalettePointerMove,
      onPalettePointerUp,
      onPalettePointerCancel,
      onPrevious: goToPreviousPaletteElement,
      onNext: goToNextPaletteElement,
      onItemRef,
    }),
    [
      filteredElements,
      goToNextPaletteElement,
      goToPreviousPaletteElement,
      isLandscapeCompactCanvas,
      isPaletteMoving,
      isPalettePointerActive,
      onItemRef,
      onPalettePointerCancel,
      onPalettePointerDown,
      onPalettePointerMove,
      onPalettePointerUp,
      onPaletteScroll,
      overlayClassName,
      overlayRef,
      paletteEdgePadding,
      paletteRowClassName,
      paletteViewportRef,
      paletteViewportWrapperClassName,
      resolvedCenterPaletteIndex,
      resolvedExpandedPaletteIndex,
    ],
  );

  return useMemo(
    () => ({
      activeView,
      bottomNoticeRef,
      canvasFrameClassName,
      canvasFrameRef,
      canvasPanelClassName,
      canvasPanelStyle,
      compactBottomNoticeClassName,
      compactBottomOverlayClassName,
      compactDisplayedEditorNotice,
      compositionRows,
      focusedComponentIndex,
      formulaDisplayValue,
      formulaPanelProps,
      interactiveViewBox,
      isLandscapeCompactCanvas,
      isPaletteSearchOpen,
      isSimplifiedView,
      molecule,
      moleculeComponentsCount: moleculeComponents.length,
      onAtomPointerDown,
      onCanvasPointerCancel,
      onCanvasPointerDown,
      onCanvasPointerMove,
      onCanvasPointerUp,
      onCanvasWheel,
      onClearPaletteSearch,
      onClosePaletteSearch,
      onPaletteSearchChange,
      onTogglePaletteSearch,
      paletteQuery,
      paletteRailProps,
      paletteSearchButtonClassName,
      paletteSearchInnerStyle,
      paletteSearchPanelStyle,
      paletteSearchRailRef,
      paletteSearchRailStyle,
      paletteSearchShellClassName,
      paletteSearchTriggerStyle,
      resolvedEditorNotice,
      searchInputRef,
      shouldShowActivePaletteFilter: hasActivePaletteFilter,
      simplifiedViewStyle,
      svgRef,
      toolRailProps,
    }),
    [
      activeView,
      bottomNoticeRef,
      canvasFrameClassName,
      canvasFrameRef,
      canvasPanelClassName,
      canvasPanelStyle,
      compactBottomNoticeClassName,
      compactBottomOverlayClassName,
      compactDisplayedEditorNotice,
      compositionRows,
      focusedComponentIndex,
      formulaDisplayValue,
      formulaPanelProps,
      hasActivePaletteFilter,
      interactiveViewBox,
      isLandscapeCompactCanvas,
      isPaletteSearchOpen,
      isSimplifiedView,
      molecule,
      moleculeComponents.length,
      onAtomPointerDown,
      onCanvasPointerCancel,
      onCanvasPointerDown,
      onCanvasPointerMove,
      onCanvasPointerUp,
      onCanvasWheel,
      onClearPaletteSearch,
      onClosePaletteSearch,
      onPaletteSearchChange,
      onTogglePaletteSearch,
      paletteQuery,
      paletteRailProps,
      paletteSearchButtonClassName,
      paletteSearchInnerStyle,
      paletteSearchPanelStyle,
      paletteSearchRailRef,
      paletteSearchRailStyle,
      paletteSearchShellClassName,
      paletteSearchTriggerStyle,
      resolvedEditorNotice,
      searchInputRef,
      simplifiedViewStyle,
      svgRef,
      toolRailProps,
    ],
  );
}
