'use client';

import { useMemo } from 'react';

import type { ToolRailProps } from '@/components/organisms/molecular-editor/moleculeEditorPanelShared.types';
import type { UseMoleculeEditorToolRailPropsOptions } from '@/components/organisms/molecular-editor/moleculeEditorSectionProps.types';

export default function useMoleculeEditorToolRailProps({
  activeElementMaxBondSlots,
  activeElementSymbol,
  bondOrder,
  bondOrderOptions,
  canRedo,
  canUndo,
  collapsedToolRailSectionClassName,
  effectiveToolRailCollapsed,
  expandedToolRailSectionClassName,
  floatingSaveShortcutInnerStyle,
  floatingSaveShortcutPanelStyle,
  floatingSaveShortcutTriggerStyle,
  isFloatingSaveShortcutExpanded,
  isLandscapeCompactCanvas,
  isSaveModalOpen,
  onAddSelectedElement,
  onClearSelection,
  onFloatingSaveShortcutExpandedChange,
  onOpenSaveModal,
  onRedo,
  onRemoveSelectedAtom,
  onResetMolecule,
  onSetBondOrder,
  onToggleCollapsed,
  onUndo,
  selectedAtomId,
  shouldShowFloatingSaveShortcut,
  shouldShowToolRail,
  showExpandedToolRailContent,
  summaryAtomCount,
  toolRailBodyClassName,
  toolRailCollapsedWidthClassName,
  toolRailExpandedWidthClassName,
  toolRailStyle,
}: UseMoleculeEditorToolRailPropsOptions): ToolRailProps {
  return useMemo(
    () => ({
      activeElementMaxBondSlots,
      activeElementSymbol,
      bondOrder,
      bondOrderOptions,
      canRedo,
      canUndo,
      collapsedToolRailSectionClassName,
      effectiveToolRailCollapsed,
      expandedToolRailSectionClassName,
      floatingSaveShortcutInnerStyle,
      floatingSaveShortcutPanelStyle,
      floatingSaveShortcutTriggerStyle,
      isFloatingSaveShortcutExpanded,
      isLandscapeCompactCanvas,
      isSaveModalOpen,
      onAddSelectedElement,
      onClearSelection,
      onFloatingSaveShortcutExpandedChange,
      onOpenSaveModal,
      onRedo,
      onRemoveSelectedAtom,
      onResetMolecule,
      onSetBondOrder,
      onToggleCollapsed,
      onUndo,
      selectedAtomId,
      shouldShowFloatingSaveShortcut,
      shouldShowToolRail,
      showExpandedToolRailContent,
      summaryAtomCount,
      toolRailBodyClassName,
      toolRailCollapsedWidthClassName,
      toolRailExpandedWidthClassName,
      toolRailStyle,
    }),
    [
      activeElementMaxBondSlots,
      activeElementSymbol,
      bondOrder,
      bondOrderOptions,
      canRedo,
      canUndo,
      collapsedToolRailSectionClassName,
      effectiveToolRailCollapsed,
      expandedToolRailSectionClassName,
      floatingSaveShortcutInnerStyle,
      floatingSaveShortcutPanelStyle,
      floatingSaveShortcutTriggerStyle,
      isFloatingSaveShortcutExpanded,
      isLandscapeCompactCanvas,
      isSaveModalOpen,
      onAddSelectedElement,
      onClearSelection,
      onFloatingSaveShortcutExpandedChange,
      onOpenSaveModal,
      onRedo,
      onRemoveSelectedAtom,
      onResetMolecule,
      onSetBondOrder,
      onToggleCollapsed,
      onUndo,
      selectedAtomId,
      shouldShowFloatingSaveShortcut,
      shouldShowToolRail,
      showExpandedToolRailContent,
      summaryAtomCount,
      toolRailBodyClassName,
      toolRailCollapsedWidthClassName,
      toolRailExpandedWidthClassName,
      toolRailStyle,
    ],
  );
}
